### ISSUE TITLE
Inline the known methods invocation

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#1]
Evaluate this https://github.com/dotnet/coreclr/issues/10282#issuecomment-287917174.

**Comment by dadhi** [comment]
Such things exist: https://github.com/hazzik/DelegateDecompiler

Also forgot that I did it myself quite some time ago in FunTools, to decompile method body for member access, to get the member names. like this https://www.codeproject.com/Articles/14058/Parsing-the-IL-of-a-Method-Body

**Comment by dadhi** [comment]
Let's presume we have this:

    () => store.GetOrAdd(id, () => new X())

and 

    T IStore.GetOrAdd(int id, Func<object> create)
    {
         var it = _items[id];
         if (it == null) lock(_items)
             _items[id] = it = create();
         return it;
    }

Then steps

1. Decompile and inline GeyOrAdd
2. Inline Create invocation

Q, how fast will be this?

**Comment by jogibear9988** [comment]
Do we need to decompile the delegate? Can't we include much of it's IL directly?

**Comment by dadhi** [comment]
Open question, it was a vogue idea for possible inlining variants. Problem with delegate inlining is its laziness. The code may be invoked at all by consumer.

**Comment by dadhi** [comment]
Let's conclude it with #138. Otherwise, it is too big of a thing.
