### ISSUE TITLE
Project icon

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#112]
Ideas are welcome!

**Comment by dadhi** [comment]
Maybe something alongside the [DryIoc icon](https://github.com/dadhi/DryIoc/blob/master/logo64.png)

**Comment by jogibear9988** [comment]
https://thenounproject.com/term/fast/316759/

**Comment by dadhi** [comment]
https://thenounproject.com/term/snake/1833160

**Comment by dadhi** [comment]
Here is the new icon, eat it fast: https://github.com/dadhi/FastExpressionCompiler/blob/v3-dev/logo.png
