### ISSUE TITLE
Minimize memory consumed by FEC.LightExpression.Expression

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#116]
The expression with multiple sub-expressions like `Expression.Call` contain their arguments in array. 

We may provide overloads with separate 1, 2, 3, 4, 5, or more arguments, and store them not in array but inlined.

If we futher make some expressions into a `struct`, e.g. `ParameterExpression` we can gain an additional savings.

**Comment by dzmitry-lahoda** [comment]
What way contributor may check that his changes do good in terms of performance? Could it be running all tests as part of specific bench? As of now I do not know how to do it.

**Comment by dzmitry-lahoda** [comment]
Another alternative to have limit number of params to 255 #89 and pass small array by ref and call it with by ref return. So we may store items in most optimal array instead doing overloads.

**Comment by dadhi** [comment]
@dzmitry-lahoda I will review #89, thanks for reminder

**Comment by dadhi** [comment]
Another thing what is bothering me is that FEC almost always has a Gen1, Gen2 allocations vs `Expression.Compile` does not. Check the benchmarks in #72.

**Comment by dadhi** [comment]
> We may provide overloads with separate 1, 2, 3, 4, 5, or more arguments, and store them not in array but inlined.

It is still an actual thing to look at.

**Comment by dadhi** [comment]
Added specialized versions for the  few arguments.

**Comment by dadhi** [comment]
todo:
- [ ] InvocationExpression

**Comment by dadhi** [comment]
The work is completed for all major expression, the remaining are Switch, TryCatch and Loop can be tackled separately when time permits or with contributions.
