### ISSUE TITLE
Support for Expression.Variable (in a Expression.Block)

### ISSUE THREAD

**Issue by jogibear9988** [dadhi/FastExpressionCompiler#118]
do we have already any support for Variables in Expressions? (do not think so)

whats the plan? how should we support them? should we create a new parameter for most of the methods, in wich we store all the variable expressions from a block? (like the paramExprs parameter)

**Comment by jogibear9988** [comment]
see tests in my pull req #117

**Comment by dadhi** [comment]
We do support.. to some extend, as you found not supported cases. Thanks, btw.

Regarding implementatiin, there is a `BlockInfo` stack holding the variables and respective `LocalBuilders`, it is available in `ClosureInfo`.

**Comment by jogibear9988** [comment]
found it

**Comment by jogibear9988** [comment]
see my pull req, don't know if it's a good fix, but test works
