### ISSUE TITLE
Minimize Gen1 and Gen2 allocations during compilation

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#123]
Separate issue to not forget. I would consider it rather serious.

Look at #72 benchmarks for the difference.

**Comment by jogibear9988** [comment]
Maybe we try to change "BlockInfo" to a struct and use "in" constraint (c# 7.3)

**Comment by dadhi** [comment]
We need to profile first. 

Regarding `BlockInfo` we still need to box struct to maintain a stack (struct cannot contain itself) or represent stack as an array. The latter probably a better idea.

**Comment by dadhi** [comment]
I have also some doubts about current immutable use of arrays, we are creating and copying each time we add a new value to array. May be pre-allocated list will be more suitable. 

This is a point to check.

**Comment by jogibear9988** [comment]
also arraypool could be used.
https://adamsitnik.com/Array-Pool/
but I think it for large arrays

**Comment by dadhi** [comment]
yep, for larger and with byte / struct items.

**Comment by dadhi** [comment]
No, not yet.

**Comment by dadhi** [comment]
Updated benchmarks. Looks Ok. Some more allocation shaving was done for LightExpression package.
