### ISSUE TITLE
LightExpression wrong Type

### ISSUE THREAD

**Issue by jogibear9988** [dadhi/FastExpressionCompiler#124]
The Issue 14 Tests do not work, cause the "Type" Property of Light Expression returns wrong Type.

For Example, If you create a Expression via Expression.Equals(a,b) the return Type of the BinaryExpression in MS Expressions is "bool", in FastExpression compiler it's something different depending on the compared object!

**Comment by dadhi** [comment]
Thanks for finding, I was planning to look at it next.
