### ISSUE TITLE
Net Framework Expression compiler generates perfromanter Code for isNull check

### ISSUE THREAD

**Issue by jogibear9988** [dadhi/FastExpressionCompiler#130]
If You have a IfThen expression with a check for "null" net frameworks expression compiler generates better Code!

Problem is, we could not change this in TryEmitComparison, because we need to branch over the rest of the code.

Need to look how we can do.

**Comment by jogibear9988** [comment]
left code => null check from fast expression compiler
right => from net framework

![aaa](https://user-images.githubusercontent.com/364896/44959781-ad724300-aef4-11e8-9d69-e2ac7e1a8544.png)

**Comment by jogibear9988** [comment]
@dadhi here I also need some Ideas, how we can do the check in TryEmitComparison, but the branch is outside...

**Comment by dadhi** [comment]
Probably we may enhance the `parent` passed through `TryEmit`. Instead of just an `ExpressionType`, we may combine more info into struct, and pass it by ref. 
Will it be enough?

**Comment by jogibear9988** [comment]
At this point I don't think this would help. Because the inner Function (TryEmitComparison) needs to tell the outer that it used a inverted comparison. Or should the whole comparison be generated in another way?

**Comment by jogibear9988** [comment]
Maybe I look if I add a function wich only generates a short comparison. Then I'll use it if possible ...

**Comment by jogibear9988** [comment]
I've fixed it, don't know if its a good way: https://github.com/dadhi/FastExpressionCompiler/pull/128/commits/be8ab06a9dd41f489e380b56c52f4691da6352f1
