### ISSUE TITLE
Problem with Reading & Writing of Struct Fields.

### ISSUE THREAD

**Issue by jogibear9988** [dadhi/FastExpressionCompiler#137]
We have problems with Struct Fields, because for them you need sometimes to Load the Address, sometimes the value

see failing test #136

Problem is, at the Function "TryEmitParameter" we need more information what will be done with the Parameter (wich we do not have atm). We don't know if the Variable Contains the Adress or the Value of the struct. And we don't know what will happen with it.

@dadhi good ideas how to fix?

**Comment by dadhi** [comment]
Hi again,

In theory a maximum info we can provide is the expression stack, and given that IL is also stack-based, it should be enough.. right? :)

Anyway, it seems a good idea. 
The stack frame may look like this:

    class ExpressionStack
    {
        public readonly Expression Top;
        public readonly ExpressionStack Stack;
        //.. etc.
    }

In cases where we need to store more info than just an expression, we may have an extended stack node:

    class BlockExprStack : ExpressionStack
    {
        public readonly LocalBuilder[] Vars;
        public readonly ParameterExpression[] VarExprs;
        //.. etc.
    }

Then we may remove shared `BlockInfo` stack and replace `parent` and `shouldReturnValue` with the `stack`.

What do you think?

**Comment by jogibear9988** [comment]
I think the compilation is getting slower, for example if we replace shouldReturnValue with Stack, and we often have to look back all nodes...

**Comment by dadhi** [comment]
Yep, it will..  probably marginally.
It will produce more memory garbage, that's true.

Otherwise we need an ad hoc solution.

I will play with the idea Tomortow, hopefully.

**Comment by jogibear9988** [comment]
Yeah, also when we have the Stack, we need to look when we need to emit wich command. This could also be a little bit tricky...

**Comment by jogibear9988** [comment]
I've now a fix for the current problem in #136 but I don't know if this works all of the time

**Comment by jogibear9988** [comment]
fixed for now
