### ISSUE TITLE
Optimize Compilation of nested Lambdas

### ISSUE THREAD

**Issue by jogibear9988** [dadhi/FastExpressionCompiler#138]
Net Frameworks compile of Lambda's sometimes inserts nested Lambdas directly to the Parent Lambda! See Test: Issue83_linq2db.TestLambdaInvokeSupported2 and view IL of both compiled methods

**Comment by dadhi** [comment]
Interesing, the only case for this I eould imagine in creating lambda and immefiately invoking.

**Comment by jogibear9988** [comment]
why? also when it‘s only invoked once it makes sence! why should we then do the overhead?

**Comment by dadhi** [comment]
Of course, if we can detect such cases we may inline the lambda body.

**Comment by dadhi** [comment]
We may also consider other expression reductions, like the Block with the single expression, may be others.

**Comment by jogibear9988** [comment]
as there is no code for a block emited, what would you optimize if there is only one expression contained?
could you count in the first parse round, how often a lambda is used?

**Comment by dadhi** [comment]
Regarding the emitted code for block there is no gains, but regarding infrastructure, e.g. BlockInfo, stack depth, etc. it maybe useful.

Lambda usage, may be. Need to think it out.

**Comment by dadhi** [comment]
More thoughts..

It happens that we may safely replace the labda invocation with the lambda body if has no arguments. 

For lambda with args, there is need to be a substitution process, which is unclear

**Comment by jogibear9988** [comment]
in linq2db it‘s used. and microsoft code does it.
but I think it‘s not critical. and i also dont know why we use two lambdas at linq2db.

maybe I look to fix it, when I‘ve time.

**Comment by dadhi** [comment]
@jogibear9988 fixed, check my commit for details

**Comment by jogibear9988** [comment]
Do you now inline it always? Independed of the invocation count?

**Comment by dadhi** [comment]
Yep. if you have a big-big lambda, without arguments, you may always precompile it separately. 

I doubt that it will create more cons vs pros.
