### ISSUE TITLE
String constant comparisons fail

### ISSUE THREAD

**Issue by SteveWilkes** [dadhi/FastExpressionCompiler#14]
The func created by compiling the following expression:

```C#
Expression<Func<string, bool>> expr = str => str == "Hello";
```

...does not work as expected. This is because equality comparisons created by `EmitComparison` always use `OpCodes.Ceq`, which does not work for strings (and possibly other reference types - I haven't checked).

[This StackOverflow answer](https://stackoverflow.com/questions/3060382/comparing-2-objects-and-retrieve-a-list-of-fields-with-different-values) has an example of emitting equality comparisons for reference types.

I'd be happy to submit a pull request, but my VS / ReSharper / dotnet all refuse to recognise the NUnit tests!

**Comment by dadhi** [comment]
Thanks for finding and for the SO link. Will try to fix it soon.

Btw, at the moment I am relying on NCrunch for building/testing. Wich does better that the new CLI. Stopped using R# for tests after years with NCrunch. Due this issues I've also disabled test step in _build.bat_. I am not sure that I want to spend/waste time on CI setup at the moment :( May be after couple of more updates to .net standard things.
