### ISSUE TITLE
int.MinValue access throws 'Method not supported', re: PR #152

### ISSUE THREAD

**Issue by SteveWilkes** [dadhi/FastExpressionCompiler#153]
Hi!

I've added a failing test to PR #152 - compilation of the lambda `() => int.MinValue` throws an exception from within the `DynamicILGenerator`: 'Specified method is not supported'. I'm not sure if it's anything FEC is doing, but wanted to flag it up.

Cheers,

Steve

**Comment by jogibear9988** [comment]
fix in my pull req
