### ISSUE TITLE
FastCompile with fallback could return null

### ISSUE THREAD

**Issue by detoxhby** [dadhi/FastExpressionCompiler#16]
Caused by: (and in other similar calls) https://github.com/dadhi/FastExpressionCompiler/blob/master/src/FastExpressionCompiler/FastExpressionCompiler.cs#L57

Should be:
```c#
return fastCompiled ?? (ifFastFailedReturnNull ? null : (TDelegate)(object)lambdaExpr.Compile());
```

Repro: https://dotnetfiddle.net/r4QFsf

**Comment by dadhi** [comment]
Omg! Fix will follow. Thanx a lot.

**Comment by dadhi** [comment]
@detoxhby Again thanks, added test at least

**Comment by detoxhby** [comment]
Thanks for the fast response and fix!

// I've noticed another bug with complex MemberInit that fails. Will report in the next days with example.

**Comment by dadhi** [comment]
> // I've noticed another bug with complex MemberInit that fails.

Bet, it is related to value types :(
