### ISSUE TITLE
Float - short numeric comparisons with conversions gives unexpected result

### ISSUE THREAD

**Issue by SteveWilkes** [dadhi/FastExpressionCompiler#162]
Hello!

I've added a failing test to PR #161 - similarly to issue #159, this:

```C#
((floatValue.Value >= ((float)-32768)) && (floatValue.Value <= ((float)32767)))
    ? (short?)floatValue.Value
    : default(short?);
```

...returns -8944 when `floatValue.Value` is 532. It should go to the true branch and return 532.

I've added the test to the `Issue159` test class because of the similar nature of the issues - please let me know if you'd prefer me to give it its own test class.

Cheers!

Steve

**Comment by dadhi** [comment]
That's fine, thanks. Merged.

**Comment by jogibear9988** [comment]
I've already fixed it. But I need to look, I think there are much more places in code where we need to emit a Conv_I2. We need to check that.
Also for SByte, I think a Conv_I1 maybe needed

**Comment by jogibear9988** [comment]
should work now

**Comment by SteveWilkes** [comment]
Fixed! Thanks :)

I'm having issues converting decimals and ints to doubles - I'll raise those in a separate issue.
