### ISSUE TITLE
Support Expression.Assign for parameter, field, property

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#17]

**Comment by z4kn4fein** [comment]
Hi @dadhi 

Thanks for this awesome lib, it helped me a lot to understand better this topic. If you don't mind I'd like to start work on the support of the Block and Assignment expressions if you don't started it already. I already implemented some parts of them in my emitter module for my DI container and i would be really happy to add and finish it here.

Thanks,
Peter

**Comment by dadhi** [comment]
Hi @z4kn4fein,

You can go ahead :)

**Comment by dadhi** [comment]
Hi @z4kn4fein ,

I am currently in need for Assign in DryIoc, so I have started the work already. 
Plan to implement assignment to: Parameter, Field, Property.
For the tricky cases will be returning `false` to fallback.

**Comment by z4kn4fein** [comment]
Hi @dadhi 

I'm already finished that part, if you mind i can create a PR which contains just that part. (currently i'm struggling with the block variables passing to nested lambdas) 
If you already done with it just ignore this comment :)

**Comment by dadhi** [comment]
Hey, I would like to see a PR for Assign.

**Comment by dadhi** [comment]
Or I will stop for the moment and wait until you're done.

**Comment by z4kn4fein** [comment]
Hi, okay, if you have a bit more time (because i'm travelling home now) i'll prepare the PR for Assign. If it's urgent don't wait for me, the trip will take 2-3 hours. 
Thanks!

**Comment by dadhi** [comment]
Ok, got it.. it is not so urgent.

**Comment by dadhi** [comment]
Hi @z4kn4fein,

I'll probaly release what we have here for Assign, it works fine, did not found issues yet :) The specifics of Assign in Block, may be addressed by Block. 
What do you think?

**Comment by z4kn4fein** [comment]
Hi @dadhi 

Sure, my thoughts are the same, it should be addressed by the Block part, i'm planning to finish the first step on the weekend, i'll have more time then. :)
👍 for the release!
