### ISSUE TITLE
Problems with ref parameters

### ISSUE THREAD

**Issue by rikimaru0345** [dadhi/FastExpressionCompiler#170]
I want to use FEC in [my serializer](https://github.com/rikimaru0345/Ceras).

However there are multiple cases where FEC seems to have problems with ref parameters.

How to reproduce:
- Clone Ceras
- Add conditional symbol `FAST_EXP` in the project options (will enable FEC in `DynamicObjectFormatter` and `ReferenceFormatter`)
- Start the "LiveTesting" project, if everything works it will run through with no exceptions or asserts getting triggered. 

Specifically the delegates from FEC crash with null reference exceptions while trying to use (write, read) a ref variable. When compiling the expressions normally, everything works fine.

**Comment by dadhi** [comment]
Hi, what version of DryIoc did you use?

**Comment by rikimaru0345** [comment]
I copied the FastExpressionCompiler.cs from the master branch today.

**Comment by dadhi** [comment]
Thanks. That means more work is needed.
@dzmitry-lahoda, whould you have time to look?

**Comment by dzmitry-lahoda** [comment]
i will look

**Comment by dadhi** [comment]
I did not run your tests yet.

But, if you will fidentify and distill some of the failed expressions it will speed up things.

**Comment by rikimaru0345** [comment]
Alright, this is the smallest example I could come up with.
It does not assign to ref parameters:
https://hastebin.com/esesaxetot.cs

I do not know if this is the only issue, but it definitely is a blocking bug for me (obviously need to get the updated values that the function wrote to the ref parameters)

**Comment by dadhi** [comment]
Thank you.

**Comment by dzmitry-lahoda** [comment]
I have reduce the problem with class with one field from constant as on parameter on my  branch. Same struct works fine. So one step from fix. Will fix to today or  during next several days.
