### ISSUE TITLE
Cannot compile to the required delegate type with non-generic CompileFast()

### ISSUE THREAD

**Issue by aienabled** [dadhi/FastExpressionCompiler#177]
Hello!

I've noticed that
`public static Delegate CompileFast(this LambdaExpression lambdaExpr, bool ifFastFailedReturnNull = false)`
produces an `Action<...>` instead of the exact delegate type I've set via `Expression.Lambda(exactDelegateType, ...)`. This is a breaking change in comparison to original `.Compile()` which produces the exact delegate type (I cannot cast the result of `CompileFast()` to the required delegate type as it's simply `Action<...something...>`).

For example:
```C#
var exactDelegateType = typeof(MyDelegate<>).MakeGenericType(myType);
var lambda = Expression.Lambda(exactDelegateType, ...);
Assert.Equals(lambda.Compile().GetType(),
              lambda.CompileFast(true).GetType();
```

The assert will fail as the result delegate type is different.
It seems I was able to fix this by using `lambdaExpr.Type` but I would prefer if you consider making a proper fix for this issue yourself as I'm not aware about all the possible issues related to this change.

Regards!

**Comment by dadhi** [comment]
Hi there, 
What version of FEC did you use?

**Comment by aienabled** [comment]
@dadhi, the latest one. I've tried the NuGet package beta first and then built it from the master branch.

**Comment by dadhi** [comment]
Ok, will check then, thanks for finding.
