### ISSUE TITLE
Add something like LambdaExpression.CompileToMethod

### ISSUE THREAD

**Issue by TechInterMezzo** [dadhi/FastExpressionCompiler#179]
This may sound strange, but would it be possible to add something like LambdaExpression.CompileToMethod to the public API of this library? I am experimenting with the creation of proxy classes at runtime and I would like to use Expressions to implement the methods. Sadly CompileToMethod is not part of netstandard or netcore. This library looks like it could solve the problem.

**Comment by dadhi** [comment]
What would be a purpose of such method? I mean you want a method produced by a TypeBuilder?

**Comment by dadhi** [comment]
FEC does only compilation of expression to delegate. If you have a vision for the `CompileToMethod` you may provide / describe the complete examples of FEC calls should look like. Also I am not sure that `TypeBuilder` mashinery is available in  .NET Standard, so it should be checked too.

**Comment by TechInterMezzo** [comment]
The System.Reflection.Emit package contains TypeBuilder and everything else that is necessary. It is netstandard compliant. I saw that you are already using System.Reflection.Emit.Lightweight for DynamicMethod (and ILGenerator, etc.).

To avoid an addional dependency, I think it would be best to just design a method that has an ILGenerator as a parameter instead of MethodBuilder. I think that Expression.Constants are not supported in this case, as there is no closure object. You just compile directly to the method body by passing the ILGenerator to the compilation method. The developer has the full responsibility to not do anything strange and unsupported. For non static methods you would also have to declare an additional first parameter for the instance value (this).

```csharp
MethodBuilder methodBuilder = typeBuilder.DefineMethod("MyAddMethod",
	MethodAttributes.Public | MethodAttributes.Virtual,
	CallingConventions.HasThis,
	typeof(int),
	new[] { typeof(int), typeof(int) });
ILGenerator ilGenerator = methodBuilder.GetILGenerator();

var paramThis = Expression.Parameter(typeof(object));
var paramA = Expression.Parameter(typeof(int));
var paramB = Expression.Parameter(typeof(int));
var body = Expression.Add(paramA, paramB);

body.CompileFastToGenerator(ilGenerator, paramThis, paramA, paramB);
```

The method definition could be:

`void CompileFastToGenerator(this Expression expression,  ILGenerator generator, params ParameterExpression[] parameters)`

If the return type is also needed for the compilation process, it could also be added as a parameter to the Compile method.

What do you think, would that be possible to implement without too much effort?

**Comment by dadhi** [comment]
Thanks for explanation. This seems legit. 
I am open for PR request. Or it will take me some time to implement, as I occupied with somthing else.

**Comment by dadhi** [comment]
The new method is called CompileFastToIL

**Comment by Shpendicus** [comment]
Hello Sir, i am kinda new to this entire Reflection/DynamicStuff and I am currently learning to play with IL-Gen and so, and on top I found your nice work here on github, big congrats to your work and mind! 

May I ask tho, how to actually call that code, created by the "lambda.CompileToFastIL(ilGen)"? i mean i called that and the result is true but where is that code now when I may ask ^^ (Sry if question is stupid ) I cant see its execution :/

Also: how am i able to pass the closure syntax (`(x,y) => x +y` ) to a method which expects your `FastExpression.Lightweight.Expression<Func<T0, T1>>`

Much thanks in advanced!!

**Comment by dadhi** [comment]
@Shpendicus 
> May I ask tho, how to actually call that code, created by the "lambda.CompileToFastIL(ilGen)"? i mean i called that and the result is true but where is that code now when I may ask ^^ (Sry if question is stupid ) I cant see its execution :/

Where the code is stored depends on how is the `ILGenerator` you passing to method is created.
It may be just in memory if you are creating a `DynamicMethod` or it may be from the dynamically generated assembly (which may or may not be saved to disk). 
Look here for how the method can be used https://github.com/dadhi/FastExpressionCompiler/blob/61ec1246d2f4a81db9d105d780d88a70ec2cd6f2/test/FastExpressionCompiler.IssueTests/Issue179_Add_something_like_LambdaExpression_CompileToMethod.cs#L42
The example how to save the code to disk is here (may not work on your target platform though): https://github.com/dadhi/FastExpressionCompiler/blob/61ec1246d2f4a81db9d105d780d88a70ec2cd6f2/test/FastExpressionCompiler.IssueTests/ExpressionSaveHelper.cs#L21

**Comment by Shpendicus** [comment]
@dadhi first thanks for the relatively quick response :)

Second: The only thing now I really would love to know if this is somehow possible by default or I have to workaround this
_(its not that bad either)_:

Is it possible, to transform a dynamic lambda-Expression to `FastExpressionCompiler.LightExpression.Expression` so that I can do  this: 
`public  FastExpressionCompiler.LightExpression.Expression TakeSysExpression(System.Linq.Expressions.Expression dynamicLambda)` and call it like: 
`FastExpressionCompiler.LightExpression.Expression   fastExpression =TakeSysExpression((x) => x + 100) ;`

sort of.. Cause I want to construct an Expression _(would love to use yours)_ from any lambda which is being created, if thats somehow possible. :)

Many thanks in regards!

**Comment by dadhi** [comment]
@Shpendicus Mainly answered it in #323.
In principle, it may be possible. But it requires significant mundane work, and do not have the time for it now.  I am fine to get the PR for this, though. You may look how backward conversion is implemented in the `ToExpression()`. Maybe you can do it on your side, just for the small subset of the expressions you are actually using?
