### ISSUE TITLE
Support Expression.Block

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#18]

**Comment by dadhi** [comment]
@iarovyi, The Block is not only a sequence of expressions, it is also may define variables, plus it enables the set of declarative expressions like IfElse.

For me the minimal useful/cool implementation will allow for instance, to use FEC with AutoMapper. AutoMapper is well known OOM tool, but it is not as fast as some others, e.g. ExpressMapper. AutoMapper currently uses Expression.Block and may be something else not yet supported by FEC. So if I can use FEC to improve AutoMapper perf, I would consider it as a measure of its usefulness and maturity.

Open for any other ideas as well :)

**Comment by dadhi** [comment]
I mean usefulness for a wider audience, outside of my DryIoc.

**Comment by dadhi** [comment]
mm.. and Marten :)

**Comment by iarovyi** [comment]
Thanks for explanation. I will try to implement it.
@dadhi

**Comment by dadhi** [comment]
@iarovyi, Please be aware that @z4kn4fein is also working on this, check thread for #17. 

@iarovyi, You may do something else, like `??` or ariphmetic operators.

Or may be you have an ideas how to squize more perf?

**Comment by dadhi** [comment]
hi @z4kn4fein,

I have found some time to move the FEC ahead, and re-read the code for Block emitting. What I jрфму completely missed was that you've made variables for assignment a part of closure object (hope I've got it right). 

I don't think it is an ideal, it should be local variable instead. The only exception is crossing the nested lambda borders, when we need store the variable in closure. 

So fyi, I am planning to address this by introducing the stack of Variables defined in respective nested block. The variable will be a pair of ParameterExpr and LocalBuilder, so we may Stloc, Ldloc variable where it is needed. 

It is also important for implementing the TryCatch. 

If you have some ideas or doubts please share.

**Comment by z4kn4fein** [comment]
hi @dadhi 

Yes, you are right, i also noticed this mistake and had the exact same thoughts about the solution like: use local variables instead and move only those to the closure which are used by a nested lambda.

I also wanted to implement that solution here (but you were faster :) ), but i thought i'll try it out in my own project first, which i almost finished yesterday working with this way.

If you mind and if you don't started the work on it already i'll be happy to adapt it in FC. On the weekend i think i'll have enough time to do it, so let me know if you are interested. :)

**Comment by dadhi** [comment]
@z4kn4fein, Cool happy to wait for your changes.

Just sharing couple of thoughts how it may be implemented. We are already have a stack of block expressions, may be we can combine the block with the defined local variables (`LocalBuilder`) associated with the parameter what's is this variable for.  Then the `DefinedVariables` may be not needed anymore.

As the result `ClosureInfo closure` argument more and more looking like context propagated through emit method, and not really a closure related. But I am OK with this for now. We may rename it later.

Btw, I have pushed some small cleanups, but nothing big.

**Comment by dadhi** [comment]
I will close the issue .  If someone will want specific case covered please open the respective new issue.
