### ISSUE TITLE
Support Expression.Loop

### ISSUE THREAD

**Issue by SteveWilkes** [dadhi/FastExpressionCompiler#180]
Hello again!

FEC falls back to `Expression.Compile()` for many of the expressions I'm looking to compile because `LoopExpression`s aren't supported. Is this something you're planning to include?

[This SO question](https://stackoverflow.com/questions/21629505/defining-a-method-with-for-loops-and-conditional-statements) looks like it demonstrates emitting a loop - unfortunately just not quite clearly enough for me to attempt a PR :P

All the best,

Steve

**Comment by dadhi** [comment]
I did not plan for lool myself, and honestly occupied with other things at the moment. 
But I am open for PR. I don't think that emitting loop is hard, at least for specific cases. You may decompile to IL the loop(s) used by your scenarios, look at them as exsample, and implement only those.. falling back for the rest.

**Comment by SteveWilkes** [comment]
I'll try it out and see how I get on :)

**Comment by SteveWilkes** [comment]
All done! Thanks! :)
