### ISSUE TITLE
ExpressionCompiler.EmittingVisitor.TryEmitIncDecAssign assumes ParameterExpression Operand

### ISSUE THREAD

**Issue by LordZoltan** [dadhi/FastExpressionCompiler#181]
I'm investigating switching to `CompileFast` for my IOC container - [Rezolver](http://rezolver.co.uk).

Upon the switch, I have some failing tests, one of which is related to an expression which contains a `PreIncrementAssign` unary expression which [increments the value of a property on a type](https://github.com/ZolutionSoftware/Rezolver/blob/d70c4fd1133716c8cfc35dc96e0a8e77826fb517/test/Rezolver.Tests.Examples/SingletonExamples.cs#L117):

![image](https://user-images.githubusercontent.com/1826395/53293914-dce37780-37d4-11e9-8949-755f94ae5cbb.png)

> Note that the `ExpressionTarget` class here is specific to Rezolver and is used as a holder for the actual expression that we want to use to produce a value - in this case, it's result of incrementing an integer property on the `CounterHolder` type.

When FastExpressionCompiler attempts to compile it, I get an `InvalidCastException` from the `TryEmitIncDecAssign` method here:

![image](https://user-images.githubusercontent.com/1826395/53293904-b8879b00-37d4-11e9-865c-d5b145286030.png)

So, it appears that the operand is assumed always to be either a supplied argument, or a local.

**Comment by dadhi** [comment]
Hi, I am not sure the cast is the root problem from the given description.

Could you add a failing (ignored) test into `IssuesTests` project and PR me? The fix is also welcome :) but the test is the good start.

**Comment by LordZoltan** [comment]
I thought the same, actually - my guess is there's something further up which is expected to have rewritten the expression or otherwise steered the compilation down a different path.

Yep, happy to add a test for repro purposes, and if I can figure out a solution I'll try to do it too :)

**Comment by LordZoltan** [comment]
On a separate note I'm having some other issues with building non-Func delegate types, so I'll see about adding those, too.

**Comment by LordZoltan** [comment]
I'm having trouble isolating the non-Func delegate issues - Rezolver often builds lots of nested lambdas, and it's happening when the return type of the function being built is, say, `delegate Bar Foo()` instead of `Func<Bar>` - I'll keep investigating that after some other refactoring I'm doing and raise another issue if I can.
