### ISSUE TITLE
InvalidCastException for TypeAs

### ISSUE THREAD

**Issue by samcragg** [dadhi/FastExpressionCompiler#185]
Trying to replace some of my expressions with LightExpression (version 2.0.0) and the following causes an exception `Unable to cast object of type 'FastExpressionCompiler.LightExpression.TypeBinaryExpression' to type 'FastExpressionCompiler.LightExpression.UnaryExpression'.`

```C#
ParameterExpression parameter = Expression.Parameter(typeof(object));
            Func<object, string> tryCast =
                Expression.Lambda<Func<object, string>>(
                    Expression.TypeAs(parameter, typeof(string)),
                    parameter
                ).CompileFast();
```
Happy to take a stab at a PR if you like?

**Comment by dadhi** [comment]
Yep, would be great!
