### ISSUE TITLE
Nested CallExpression causes System.AccessViolationException

### ISSUE THREAD

**Issue by detoxhby** [dadhi/FastExpressionCompiler#19]
Protected memory access problem.

Repro: https://dotnetfiddle.net/kK7EvY

**Comment by dadhi** [comment]
Thanks for the test! Will check.

May be we need to control supported expr types on the Client side, so that you may disable the culprit until fixed ?

**Comment by detoxhby** [comment]
Could you please explain the "Client side" scope you referred a bit more detailful in this context?

**Comment by dadhi** [comment]
By client I mean the general consumer of the FEC. Like to provide a way to configure FEC:

  
 ExpressionCompiler.Exclude(ExpressionType.MemberIbit, other);

**Comment by detoxhby** [comment]
@dadhi seems like a good idea, but I would reverse it and exclude unsupported expressions by default with API support to include them.
This way FEC would be always safe and would allow future development to enable new features progressively as they become stable.

**Comment by dadhi** [comment]
We can have both :)

**Comment by dadhi** [comment]
But better no config at all )
