### ISSUE TITLE
Parent block variable not found in TryEmitIncDecAssign

### ISSUE THREAD

**Issue by SteveWilkes** [dadhi/FastExpressionCompiler#190]
In this structure:

1. Block with variables
   2. Block with variables

...block 2 is sometimes unable to access variables belonging to block 1, as variables are sometimes accessed (e.g. in `TryEmitIncDecAssign()`) using `closure.CurrentBlock.VarExprs.GetFirstIndex(paramExpr)`, and `TryEmit`'s `Block` handler sets `CurrentBlock` to block 2.

I'm just adding this issue for tracking - I'll submit a PR with a fix :)

**Comment by dadhi** [comment]
Does it relate to #181 ?

**Comment by SteveWilkes** [comment]
Doesn't look like it, but I'm not sure - I'd be happy to take a look at that, now I'm a bit more familiar with the source code.

Closing this one! Cheers! :)

**Comment by SteveWilkes** [comment]
Btw - in case you didn't already know - VS2019 now supports custom visualizers for .NET Core projects, which means [my ReadableExpressions Expression visualizers](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1232914.ReadableExpressionsVisualizers) can now be used to view Expressions in the FEC unit tests! :)

**Comment by dadhi** [comment]
> Btw - in case you didn't already know - VS2019 now supports custom visualizers for .NET Core projects, which means my ReadableExpressions Expression visualizers can now be used to view Expressions in the FEC unit tests! :)

Missed this. It is great! Thanks.
