### ISSUE TITLE
Support for GotoExpression values

### ISSUE THREAD

**Issue by SteveWilkes** [dadhi/FastExpressionCompiler#192]
`TryEmitGoto` is marked with a TODO for supporting `GotoExpression` values - I'd like to have a try at implementing this, at least for some scenarios.

`Expression.Return()` creates a `GotoExpression` of `GotoExpressionKind.Return`, which needs to know if it's being emitted within a `Try` expression, as `OpCodes.Leave` must then be used instead of `OpCodes.Ret`. `Leave` needs access to the `returnLabel` and `returnResult` defined in `TryEmitTryCatchFinallyBlock`.

I'm therefore thinking I should:

1. Add `ParentFlags.Try` to indicate if code is being emitted within a Try
2. Add a `TryCatchFinallyInfo` class - similar to `BlockInfo` - to own `returnLabel` and `returnResult`
3. Add `PushTry()` and `PopTry()` methods to `ClosureInfo`, used similarly to `PushBlock()` and `PopBlock()`
4. Update `TryEmitGoto()` to emit `GotoExpression` values and support `GotoExpressionKind.Return`, using `OpCodes.Ret` or `OpCodes.Leave` as appropriate

Before I get started, please could you let me know if this sounds like an acceptable / sensible approach?

Cheers,

Steve

**Comment by dadhi** [comment]
Hi, seems sensible but only implementation will show.. go ahead.

**Comment by dadhi** [comment]
PR is merged.

**Comment by SteveWilkes** [comment]
All done! Thanks :)

**Comment by dadhi** [comment]
@SteveWilkes 

Hi Steve, I have the problems with the recent AutoMapper related #196 and #197 issues - basically those are problems with `Block` emitting in some cases. I have created the fix, but it broke the `Expression.Return` (search for `Ignore("fix me")`).

I tried to fix both cases and the Return together, but did not succeed :(

My question is how **Important** this feature for you? Could we postpone this Return Label for later.

I would commit my changes directly to master. But the changes related to the 4 broken tests are small and mostly done in `TryEmitTryCatchFinallyBlock` where I am not creating the variable to store `TryCatch` result if the `TryCatch` has `ParentFlags.IgnoreResult` (is not the last expression in `Block`).

**Comment by dadhi** [comment]
TBD Don't forget to enable fallback if the feature is turned off.

**Comment by SteveWilkes** [comment]
I use `Expression.Return` to short-circuit execution in certain cases, so it's essential for my uses. I'll take a look at the failing tests and get back to you!

**Comment by SteveWilkes** [comment]
Fixed by PR #200 :)
