### ISSUE TITLE
Null Reference Exception on Expression.Property

### ISSUE THREAD

**Issue by mayoatte** [dadhi/FastExpressionCompiler#198]
Hello,

I'm getting a null (and hence a null reference exception) when I create a property expression using the name of the property. Here's the code.

![image](https://user-images.githubusercontent.com/29760620/58756399-ec95ea80-84ac-11e9-81f0-658d708096b7.png)

The argumentsArray expression comes back with a null member.

I'm not sure what it is about my setup that causes (maybe because TContext is generic?) this but i don't run into the issue if i switch back to System.Linq.Expressions. 

PS. Thank you for your awesome library.

**Comment by dadhi** [comment]
Thanks, What is the FEC version?

**Comment by mayoatte** [comment]
2.0.0

**Comment by dadhi** [comment]
Seems like LightExpression did not look into base properties.  
It would be also better to throw an expression to avoid surprises.

**Comment by mayoatte** [comment]
Thanks for looking into this so quickly!
