### ISSUE TITLE
cast int->ulong creates invalid delegates.

### ISSUE THREAD

**Issue by EamonNerbonne** [dadhi/FastExpressionCompiler#2]
```C#
ExpressionCompiler.Compile( () => 0UL == (ulong)"x".Length)();  //NullReferenceException
ExpressionCompiler.Compile( () => 0UL == (ulong)DateTime.Now.Day)();//Process dies
```

The second one is scary; there's a chance this is a security issue in .NET.  It reports that...

The process was terminated due to an internal error in the .NET Runtime at IP 00007FFD35C25C22 (00007FFD35B90000) with exit code 80131506.

I would have expected an InvalidProgramException or something rather than that, but I'm not too familiar with the internals, so who knows...

**Comment by dadhi** [comment]
Nice one, and thanks for tests. Will check other casts as well.

**Comment by EamonNerbonne** [comment]
Thanks for the library!

**Comment by dadhi** [comment]
Pushed [preview-04](https://www.nuget.org/packages/FastExpressionCompiler/1.0.0-preview-04) which is partially fixes the bug and fallbacks on some other cases (`ulong` constants).
