### ISSUE TITLE
StrongNaming missing

### ISSUE THREAD

**Issue by qlikTERror** [dadhi/FastExpressionCompiler#21]
The fact there is no strong name for this kind of assembly avoids us to use it from other strong named assemblies.

**Comment by dadhi** [comment]
Easy to solve with [StrongNamer](https://www.nuget.org/packages/StrongNamer). 

Here is [rationale](https://github.com/dsplaisted/strongnamer/blob/master/README.md).

**Comment by qlikTERror** [comment]
Ok, so you suggest to use it. Thank you!

**Comment by dadhi** [comment]
Sorry, I have closed on a spot, did not wait for you :|

Other option is just include the FEC single source file where you want it :) It may be even a straightforward option, if you are using Paket as NuGet client.
