### ISSUE TITLE
ExpressionType.Increment is not supported huh

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#210]

**Comment by dadhi** [comment]
Decrement is not supported too #215

**Comment by jogibear9988** [comment]
There ar emuch more.

In your unitests for UnaryExpressions, if you change from
.CompileFast()
to
.CompileFast(true)
16 Tests will fail

**Comment by jogibear9988** [comment]
@dadhi no idea why the test fails?

**Comment by dadhi** [comment]
Nope, tried it locally on **net46** and it passes. It is clearly something is off here.

**Comment by jogibear9988** [comment]
have you also looked at the IL Code? for me it seems correct

**Comment by dadhi** [comment]
did not looked into it, too deep to complete closure and nested lambdas optimizations.

**Comment by dadhi** [comment]
fixed
