### ISSUE TITLE
Incorrect code generation and unsupported expressions

### ISSUE THREAD

**Issue by dbolin** [dadhi/FastExpressionCompiler#215]
Tried to use FEC in a personal project that uses compiled expressions for its core functionality - https://github.com/dbolin/Apex.Serialization

After replacing the calls to Compile() with CompileFast(), 30 tests of out the 272 total fail. If I call CompileFast(true), 134 tests fail.

I wasn't able to run any benchmarks beyond the simplest case to see if there would be any runtime performance difference.

**Comment by dadhi** [comment]
First, what FEC version do you use?

Then as usual, it is either the same issue, or number of not related bugs. The only possibility is to fix them one by one having a smallest reproducible failing test(s) from you.

**Comment by dbolin** [comment]
I was using the master branch.  Decrement expression is currently not supported, which accounted for most if not all of the difference from disabling the fallback.

I spent some time investigating one of the failures, but wasn't able to produce a simpler case that failed based on it. I might try again later.

**Comment by dadhi** [comment]
@dbolin I have added the dedicated issue #261 to support all of the current Apex.Serialization tests and I have decent progress there in the V3 branch.
