### ISSUE TITLE
Use _S opcodes for storing and loading variables

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#218]
We can track number of used local variables in ClosureInfo.
It will be the number of `Constants.Count` + `NestedLambdas.Count` + add-hoc variable usings.

**Comment by Scooletz** [comment]
I took a look how locals are used and I think that the following code should address it without all the counting. If you agree, ping me and I'll send a PR

```csharp
public static IlExtensions
{ 
    public static void Load(this ILGenerator il, LocalBuilder var) => il.LoadVariable(var.LocalIndex);
    static void LoadVariable(this ILGenerator il, int number)
    {
        switch (number)
        {
            case 0:
                il.Emit(OpCodes.Ldloc_0);
                return;
            case 1:
                il.Emit(OpCodes.Ldloc_1);
                return;
            case 2:
                il.Emit(OpCodes.Ldloc_2);
                return;
            case 3:
                il.Emit(OpCodes.Ldloc_3);
                return;
            default:
                if (number <= byte.MaxValue)
                {
                    il.Emit(OpCodes.Ldloc_S, (sbyte)number);
                    return;
                }
                else
                {
                    il.Emit(OpCodes.Ldloc, number);
                    return;
                }
        }
    }
}
```

**Comment by dadhi** [comment]
Hi @Scooletz , glad to see you here :)

Thanks for suggestions, but similar methods were already added by @Havunen in the latest [PR](https://github.com/dadhi/FastExpressionCompiler/pull/221/files#diff-ae2cf5be7db6d225c5ac3378f92a2e03R3823)

I am currently going through the codebase making use of them.

**Comment by Scooletz** [comment]
All righty! Take care @dadhi :-)

**Comment by dadhi** [comment]
I've ended up hacking DeclareLocal so that no need to allocate LocalBuilder, which is the class btw.

**Comment by dadhi** [comment]
> I've ended up hacking DeclareLocal so that no need to allocate LocalBuilder, which is the class btw.

For some reason, I am getting more regression in invocation on AutoMapper tests with it.

> We can track the number of used local variables in ClosureInfo.
> the following code should address it without all the counting

Seems like ILGenerator already does this kind of optimization - so we don't need to do that or rather we can do it only where we need to for `Stloc, Ldloc, Ldloca`:

https://referencesource.microsoft.com/#mscorlib/system/reflection/emit/ilgenerator.cs,861

**Comment by dadhi** [comment]
＞For some reason, I am getting more regression in invocation on AutoMapper tests with it.

Linking #225
