### ISSUE TITLE
Provide an equivalent of `System.Linq.Expressions.ExpressionVisitor`

### ISSUE THREAD

**Issue by Warpten** [dadhi/FastExpressionCompiler#233]
There is currently no way to check that two `Expression`s represent the same bit of code, besides doing a simple reference check. This is also what the BCL's Expressions do, that is:

```cs
Expression a = Expression.Constant(5);
Expression b = Expression.Constant(5);
var eq = a == b; // false;
```
Is the current behavior for both FEC and the BCL's expressions.

The "standard" way to do this is to expand upon `ExpressionVisitor`, but a mirrored implementation of this type is not provided by FEC. Of course, one can convert the tree constructed from FEC to the BCL's expression, but that sort of defeats the purpose of having a fast expression type.

There are a couple ways this library could *relatively easily* fix this:
a) Straight up provide ExpressionVisitor. This would help for more than just comparing `Expression`s, but is a significant amount of work. CoreFX source can be found here: https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/src/System/Linq/Expressions/ExpressionVisitor.cs
b) More specifically for comparison, make each implementation of `Expression` implement both `IEquatable<Expression>` as well as `IEquatable<T>`. The problem would be that this is a breaking change in contrast to the BCL, as one would need to use `Object.ReferenceEquals(a, b)` instead of `a == b` to maintaing compatibility.
c) Provide an implementation IEqualityComparer<Expression>, which does the heavy lifting. This is pretty similar to option *b*, but it does not break compatibility with what the BCL provides.

There are already solutions for the BCL's expressions, but FEC is not completely feature-equivalent, especially in terms of members for each expression node

**Comment by dadhi** [comment]
> There is currently no way to check that two Expressions represent the same bit of code.

What are the use-cases for that?

**Comment by Warpten** [comment]
For me personally the main benefit of being able to compare expression trees is loop unrolling. I have a specific rule for the data I'm generating code for, which makes me have to unroll loops based on some conditions. For now I ma aged to rely purely on reference equality checks by abstracting away every complex node (method call etc) into my own types that all implement `IEquatable`, but because I still use the stock expressions front the BCL, I still pay their price.

More generally though, because I see now that the issue is very centered on my problems, providing a way to walk down an expression tree to either rewrite it, reduce it, optimize it, would imo be a welcome change especially for folks who write more complex code than just "set in stone" expression trees.

**Comment by dadhi** [comment]
So your minimal requirements whould be implementing `IEqualityComparer<>` ? 
If so, I am OK with that.  
But it is unlikely I will have time for this.. so open for PRs.






> Sorry for the possible wall of text, I'm typing this from my phone

Np ;-) 99% of time I am typing from the phone too.

**Comment by dadhi** [comment]
The work is stsrted here https://github.com/dadhi/AutoMapper/tree/FECv3

**Comment by dadhi** [comment]
done
