### ISSUE TITLE
Trying to implement For/Foreach loop but getting an InvalidProgramException thrown

### ISSUE THREAD

**Issue by thenameless314159** [dadhi/FastExpressionCompiler#237]
Hello i've been trying to implement a network-oriented serialization logic powered by expression tree and more specifically your light expression with support of the latest binary and pipelines API such as SequenceReader<byte> etc... 

At first I tought it was because of my own for/foreach loop implemented in expression tree (using an home made wrapper around ET for abstraction purpose), here are my tests and the output expression (printed using AgileObjects.ReadableExpressions) : 

![forforeachtests](https://user-images.githubusercontent.com/22622473/71563095-61a0c100-2a8a-11ea-9986-a326617cbf6a.png)

But then I refactored my serialization logic to call a static extensions method which does the foreach loop in a method instead of generated using the ET and I still had some tests that failed. 

I made a gist of an output expression (still using AgileObjects) here : https://gist.github.com/thenameless314159/ac90b435d24d84c42521fea0f3124a19

(Note: the expr printer might been broken bc it print my static extensions methods with 'this ref' as a regular call with the first parameter in ref (which is not of course))

And here is a screen of my testing logic and how the expression looked before refactoring :

![devenv_hUUUYN5ps3](https://user-images.githubusercontent.com/22622473/71563108-85640700-2a8a-11ea-8e44-cce537436d66.png)

My whole unit-tests does pass with the BCL expression compiler, also the expression compilation tests does pass using the lightexpressions and .CompileFast(), the System.InvalidProgramException is only thrown when the compiled delegate is invoked. Here are the tests that fails :

![mFWbue1iTN](https://user-images.githubusercontent.com/22622473/71562994-2356d200-2a89-11ea-9cc7-23ad95897adb.png)

If you need any more informations please tell me.
And thank your very much for your library it is awesome and the bench on the front page seems wonderfull !

**Comment by dadhi** [comment]
Hi, could you instead of AgileObjects reconstruct the expression with `LightExpression.Expression.ToCodeString`
Then could you put it into the test in IssueTests project and open a PR for me?

**Comment by thenameless314159** [comment]
I'm not used to git tools for anything else than commit or CI, as a self-learning developer working on teams is not my main my focus therefore i've never made a PR before :/

So i'm unsure about what you want me to commit as a pull request ? In fact I was trying to use .ToCodeString before but I didn't get satisfyign readable expresssions :/ Thanks to the abstr over the expressions i've made I can swith to fast compilation with only somes lines to refactor whithout having to change anything else on my expr gen logic (I can share you the class if you want)

![image](https://user-images.githubusercontent.com/22622473/71575094-e5d76080-2aeb-11ea-8bb8-54f09ed24301.png)

I get this output for the SumWithForEachLoop test : 

```csharp
Lambda(typeof(Func<int32, int32>),
Block(
typeof(int32),
new ParameterExpression[]{ Parameter(typeof(int32), "current"),Parameter(typeof(int32), "result") },
Block(
typeof(Void),
new ParameterExpression[]{ Parameter(typeof(IEnumerator<int32>), "int32Enumerator") },
Assign(Parameter(typeof(IEnumerator<int32>), "int32Enumerator"), Call(Convert(Parameter(typeof(int32), "values"), typeof(IEnumerable<int32>)),
typeof(IEnumerable<int32>).GetTypeInfo().GetDeclaredMethods("GetEnumerator").ToArray()[0],
new Expression[0])),Loop(Condition(Equal(
Call(Parameter(typeof(IEnumerator<int32>), "int32Enumerator"),
typeof(IEnumerator).GetTypeInfo().GetDeclaredMethods("MoveNext").ToArray()[0],
new Expression[0]),
Constant(true, typeof(Boolean))),
Block(
typeof(int32),
new ParameterExpression[]{ Parameter(typeof(int32), "current") },
Assign(Parameter(typeof(int32), "current"), Property(Parameter(typeof(IEnumerator<int32>), "int32Enumerator"),
typeof(IEnumerator<int32>).GetTypeInfo().DeclaredProperties.ToArray()[0])),AddAssign(Parameter(typeof(int32), "result"), Parameter(typeof(int32), "current"))),
Goto(loopBreak, typeof(Void)),
typeof(Void)),
Label("break"))),Goto(UnamedLabel, Parameter(typeof(int32), "result"), typeof(int32)),Label(UnamedLabel, Constant(0, typeof(int32)))),
Parameter(typeof(int32), "values"))```

Do I have to reconstruct the serialization expression on a pull request ? Because it's a wide project with several layers it'd take me too long to reimplement it :/

**Comment by dadhi** [comment]
> but shouldn't we first identify which part of the expr is concretely causing trouble instead of me adding my big expr into the tests

You are right about this but usually, we need something to start working with.
Given that the expressions you posted are compiled wrongly - we can start with them, 
debug them and experiment with stripping the none relevant parts.

If you don't have time for PR, I may start with what you posted above... well when I have time for this.

**Comment by thenameless314159** [comment]
> Given that the expressions you posted are compiled wrongly 

Is it ? I mean, am I doing a bad or over-complicated ET ? A friend of mine told me it wasn't relevant to log errors on deserialize with Trace.TraceWarning maybe I should remove this part ? But since it's just a static method call I don't think it would solve anything ?

I do have time for this, but also this is not a priority since I do have decent performance atm with the bcl compiler and my project is still under development :

![ApplicationFrameHost_5IUEciA2p4](https://user-images.githubusercontent.com/22622473/71579407-a82f0380-2afc-11ea-9200-36cd334c8047.png)

So no need to hurry at all !

**Comment by thenameless314159** [comment]
Hello it's me again, i've seen that your issuetest assembly is in .net core 2.0 which does not support ReadOnlySequence<T> which prevent me from implementing my expression :/ I'll wait for an update then

**Comment by dadhi** [comment]
I've added netcoreapp2.2 target, is it enough?

**Comment by thenameless314159** [comment]
I believe .NET Core 3.0 is needed

**Comment by dadhi** [comment]
Here docs are saying that it is supported from nc2.1 https://apisof.net/catalog/System.Buffers.ReadOnlySequence%3CT%3E

**Comment by thenameless314159** [comment]
My apologies I meant that the SequenceReader<T> was parts of the .net core 3.0 update and is also required for my expressions. Also I must add System.Memory as a nuget package in your IssueTest assembly to use ReadOnlySequence<T> and I can't use the string.Create() method which is also strange. Why don't you update to .NET Core 3.1 since there are little or zero breaking changes in those updates ? I believe LTS is always better

**Comment by dadhi** [comment]
Hi, 
The problem is CI setup - it requires time to configure.
For now, I have added the 3.1 to IssueTests and LE.IssueTests working in "DevMode" on your machine but it will be turned off on CI for now - https://github.com/dadhi/FastExpressionCompiler/pull/239
So just use `#ifdef netcoreapp3.1` until we are in a better position.

**Comment by thenameless314159** [comment]
I can't manage to create a pull request so I made a gist with the tests 

https://gist.github.com/thenameless314159/38c916cfe1355b76a50b84759f1be6b3

Is it allright ?

**Comment by dadhi** [comment]
It will do, thanks. I will look when I have time.

**Comment by thenameless314159** [comment]
Thank you very much, have fun !

**Comment by thenameless314159** [comment]
Oh and I forgot, it might be an error relative to the way I handle returning value from a function ? Because within your solution the exception thrown is from the compilation not at the call of the compiled delegae therefore it provided me with the details that it was the GotoExpression that failed converting

**Comment by dadhi** [comment]
I *love* GotoExpression, thanks for the info

**Comment by dadhi** [comment]
Note for myself to add the benchmark for the tested code, because the code is the part of real-world usage and not some syntethic thingy. Also it utilizes more complex beyond the hello-world examples.

**Comment by dadhi** [comment]
@thenameless314159 
Hi, sorry for super late update. 
I still have the with test code, but it seems the problem in a code itself. 
I have "reversed" the code from the expressions to C# but the test fails starting from the reading of `contentLength`
https://github.com/dadhi/FastExpressionCompiler/blob/504320a937f411dbfaf5b7865faabf94bc7da8b8/test/FastExpressionCompiler.IssueTests/Issue237_Trying_to_implement_For_Foreach_loop_but_getting_an_InvalidProgramException_thrown.cs#L41

**Comment by dadhi** [comment]
@thenameless314159 

Fixed the test (at least for the sake of compilation).

In addition, I have run a benchmark:

```md
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18363
Intel Core i7-8565U CPU 1.80GHz (Whiskey Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.302
  [Host]     : .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT
  DefaultJob : .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT

### Expression and LightExpression creation and compilation

|       Method |        Mean |     Error |     StdDev | Ratio | RatioSD |  Gen 0 |  Gen 1 |  Gen 2 | Allocated |
|------------- |------------:|----------:|-----------:|------:|--------:|-------:|-------:|-------:|----------:|
| CompiledFast |    80.68 us |  1.609 us |   3.499 us |  1.00 |    0.00 | 3.9063 | 1.9531 | 0.1221 |  16.06 KB |
|     Compiled | 4,442.98 us | 88.213 us | 191.768 us | 55.15 |    3.05 |      - |      - |      - |  27.55 KB |

### Invoking deserializer

|              Method |     Mean |     Error |    StdDev |   Median | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------- |---------:|----------:|----------:|---------:|------:|--------:|-------:|------:|------:|----------:|
| Invoke_CompiledFast | 1.113 us | 0.0210 us | 0.0384 us | 1.132 us |  1.00 |    0.00 | 0.0954 |     - |     - |     400 B |
|     Invoke_Compiled | 1.097 us | 0.0221 us | 0.0535 us | 1.090 us |  0.99 |    0.06 | 0.0992 |     - |     - |     424 B |


```

**Comment by dadhi** [comment]
@thenameless314159 

Btw, I have much better C# expression to code printer now (at least comparing to the one posted by you produced by AgileObjects.ReadableExressions). Because the produced code is compile-able, I was able test the test code and spot the bugs.

I would like to test other cases as well... but did not found your project in a public repos.

**Comment by thenameless314159** [comment]
I released the generic APIs for serialization on this repo https://github.com/thenameless314159/Andromeda.Serialization but without any expression related logic, the only thing I did is to provide a [method builder abstraction](https://github.com/thenameless314159/Andromeda.Serialization/blob/main/src/Andromeda.Serialization/SerializationMethodBuilder.cs) to implement with either expression tree compilation or anything else (for example a reflection based with binary converters method builder like in System.Text.Json serialization). 

So if you feel like making a serialization method builder expression tree based you should definitely do it since I won't share my expression-based implemented serialization method builder. (because it's currently implemented for a specific kind of protocol, if I ever refactor it in a more generic way i'll publish it of course)
