### ISSUE TITLE
Implement FEC own expression to csharp code ToCSharpString

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#240]
Should help to avoid dependency on ExpressionToCodeLib in such scenarios https://github.com/dadhi/DryIoc/issues/101

It will also prevent double conversion from LightExpression to Linq.Expressions, then to code.

**Comment by dzmitry-lahoda** [comment]
May be LightExpression should be converted into Roslyn AST? At least that is ecosystematically right.

**Comment by dadhi** [comment]
I need a conversion of the small subset of Expressions first and falling back to `ToString` for the rest. Anyway, it doesn't prevent the usage ExpressionToCodeLib if you need the full-blown to-code conversion. Rather it should extend the FEC debug view possibilities without additional dependencies.

I did the work of improving the `CodeString` performance and functionality already in the scope of https://github.com/dadhi/DryIoc/pull/268
So the work on `CSharpCodeString` looks more simple task following the `CodeString` template.

**Comment by dadhi** [comment]
mainly completed, the remaining issues if found may be addressed separately.
