### ISSUE TITLE
Consider using continuous integration

### ISSUE THREAD

**Issue by JediMasterSam** [dadhi/FastExpressionCompiler#245]
It seems the nuget packages are very far behind compared to the repository (I believe it is using commit ec9209c51df947c102ef2e51201418e3558e7e76).  I noticed this when I was having an issue replacing` System.Linq.Expesssions.Expression` with `FastExpressionCompiler.LightExpression.Expression` because _Subtract_ is spelled _Substract_.  The typo was corrected in the more recent revisions, so it would be nice to have that along with the other changes in the nuget package.

**Comment by dadhi** [comment]
Hi,

I am planning to release V3 preview on a nuget.
Hope, it is fine with you.
