### ISSUE TITLE
Calling method with in/out parameters in expression lead to NullReferenceException on calling site.

### ISSUE THREAD

**Issue by martynovs** [dadhi/FastExpressionCompiler#248]
I'm generating lambda to serialize struct field:

```csharp
public interface ISerializer
{
   void WriteDecimal(in decimal value);
}

public struct Test 
{
    public decimal Field1;
}

public delegate void SerializerDelegate(ISerializer serializer, ref Test data);

var serializer = Expression.Parameter(typeof(ISerializer), "serializer");
var method = typeof(ISerializer).GetMethod("WriteDecimal");
var data = Expression.Parameter(typeof(Test).MakeByRefType(), "data");
var field = Expression.Field(data, typeof(Test).GetField("Field1"));
var call = Expression.Call(serializer, method, field);
var serialize = Expression.Lambda<SerializerDelegate>(call, serializer, data).CompileFast();
```

When compiled with LINQ it worked fine,  but fails when i'm using `CompileFast`.
Calling `serialize` throws `NullReferenceException` inside `WriteDecimal` when serializer accessing `value`.

**Comment by martynovs** [comment]
Same issue with `out` parameters. Assigning value to parameter on calling site throws `NullReferenceException`.

**Comment by dadhi** [comment]
Will check, thanks

**Comment by dadhi** [comment]
@martynovs Hi, seems like this week I won't have the time either to look into this.
Maybe you can proceed yourself with PR?

Given that your sample is pretty small you may add it into IssuesTests project (check the other files in this project for the inspiration).

Then fix the test: look into the decompiled IL you want to get and compare with the one produced by FEC, debug to see where things go wrong...

**Comment by dadhi** [comment]
@martynovs I have added the test and it is passing just fine https://github.com/dadhi/FastExpressionCompiler/commit/28a28e32fe80ce44486b53decf28081f47523701

Maybe you can check?

**Comment by dadhi** [comment]
Ok, something wrong on Linux.. going check the generated IL next
