### ISSUE TITLE
Bad code-gen for byRef parameters

### ISSUE THREAD

**Issue by kindermannhubert** [dadhi/FastExpressionCompiler#251]
Simplified example:
```C#
using static System.Linq.Expressions.Expression;

public static class Test
{
    public delegate bool EqualsHandler(in double a, in double b);

    public static EqualsHandler Create()
    {
        var leftParameterExpr = Parameter(typeof(double).MakeByRefType(), "leftValue");
        var rightParameterExpr = Parameter(typeof(double).MakeByRefType(), "rightValue");
        var equalsMethod = typeof(double).GetMethod(nameof(IEquatable<object>.Equals), new[] { typeof(double) });
        var callExpr = Call(leftParameterExpr, equalsMethod, rightParameterExpr);
        return Lambda<EqualsHandler>(callExpr, leftParameterExpr, rightParameterExpr).CompileFast();
    }
}
```
Produces bad code-gen with 2.0.0 nuget and not even with (at time of writing) latest 5a3d4baa775e616b722f3b56513c2000edf7ebb9. Code-gen is different but wrong for both.

For nuget 2.0.0:
![image](https://user-images.githubusercontent.com/11704036/81788184-6bd7cf00-9502-11ea-970d-e359049f1d90.png)

For 5a3d4baa775e616b722f3b56513c2000edf7ebb9:
![image](https://user-images.githubusercontent.com/11704036/81789901-edc8f780-9504-11ea-9b87-1a716ee74c97.png)

There should be only one 'ldind' instruction applied to second argument. Call has to be done on address (first argument already is reference). This is correct output of system Compile:
![image](https://user-images.githubusercontent.com/11704036/81790193-5617d900-9505-11ea-8ef2-3deb4a1d1177.png)

Also there can be used 'call' instruction instead of 'constrained callvirt'.

And now I'm quiet not sure why does 'closure' parameters are present in last two outputs..? I would definitely expect signature of first output (2.0.0) because there should not be any closure in this case.

Thanks!

**Comment by dadhi** [comment]
Thanks for reporting, I will look when I have time but it may be delayed. PRs are welcome as well.

> And now I'm quiet not sure why does 'closure' parameters are present in last two outputs..? I would definitely expect signature of first output (2.0.0) because there should not be any closure in this case.

The FEC always compiles delegate with the (empty) closure even for "static" delegates because the resilt delegate is faster than the one without the closure.
