### ISSUE TITLE
Bad code-gen for comparison of nullable type to null

### ISSUE THREAD

**Issue by kindermannhubert** [dadhi/FastExpressionCompiler#252]
Simplified example:
```C#
using static System.Linq.Expressions.Expression;

public static class Test
{
    public delegate void Handler(int? value);

    public static Handler Create()
    {
        var parameterExpr = Parameter(typeof(int?), "value");
        var toStringMethod = typeof(int?).GetMethod(nameof(object.ToString));
        var callExpr = Call(parameterExpr, toStringMethod);
        var callIfNotNull = IfThen(Not(Equal(parameterExpr, Constant(null, typeof(int?)))), callExpr);
        return Lambda<Handler>(callIfNotNull, parameterExpr).CompileFast();
    }
}
```

For 2.0.0 nuget:
![image](https://user-images.githubusercontent.com/11704036/81793811-2919f500-950a-11ea-9325-e0f44d61a1aa.png)

For 5a3d4ba:
![image](https://user-images.githubusercontent.com/11704036/81793350-89f4fd80-9509-11ea-98e3-962c3adddfe5.png)
Didn't try to understand it, but looks overly complex (and failing while executing).

This is correct output of system Compile:
![image](https://user-images.githubusercontent.com/11704036/81793203-54501480-9509-11ea-946b-e92a61858904.png)

**Comment by dadhi** [comment]
This is a cool find. Will look when I have time. I am open for PRs.
