### ISSUE TITLE
Unable to save Assembly with nested Lambda

### ISSUE THREAD

**Issue by ackava** [dadhi/FastExpressionCompiler#268]
I have an Expression which contains nested lambda with closure. It gives following error "The IL Generator cannot be used while there are unclosed exceptions" while saving the assembly. 

It seems the error is little misleading but what it means that to save Assembly, inline lambda must be converted to Delegates with Concrete types without closures.

I think we can pass TypeBuilder and FastExpressionCompiler can use TypeBuilder to create types for closures.

**Comment by dadhi** [comment]
@ackava Hello, this a very interesting finding. 
I did not try to save expr. with nested lambdas to the assembly before.

I am compiling the nested lambdas to separate delegates via DynamicMethod and storing them in the closure (my own array based type) of the parent lambda. And the result is 20-50x faster in invocation benchmarks. So I don't want to change the mechanism. I am using it in the DryIoc heavely.

I think that the saving to the assemby is the more rare case. But I am open for the opt-in mechanism, especially if someone supplies the PR.
From my side it will be postponed until I'll have time or absolutly need it myself.

**Comment by ackava** [comment]
@dadhi Is it possible to expose your own Array based parent lambda so it can be serialized in the assembly? I will take a look at the source and will find out and will try to submit PR.

The problem is, .net standard and .net core does not have `LambdaExpression.CompileToMethod`, and nor it gives the IL, so your library is very helpful in serializing the IL in assembly using `Lokad.ILPack`.

The problem lies in .Net's Method builder which complains that exception block is not closed, basically it is not expecting inline lambda.

**Comment by dadhi** [comment]
> Is it possible to expose your own Array based parent lambda.

What do you mean? How to expose? 

> basically it is not expecting inline lambda.

Hmm, don't undersdand that. You mean it wants the method group instead of the delegate or something?

**Comment by dadhi** [comment]
@ackava 

I've checked that the closure classes are public `ArrayClosure` and `ArrayClosureWithNonPassedParams` in code.

If you need some help or questions regarding the internals don't hesitate to ask.

**Comment by ackava** [comment]
@dadhi You can close this issue as I have created an alternative in YantraJS library, however, here are few points,

1. Saving and Reloading assembly is slower compared to generating code when needed scenario, JIT is fast.
2. Assembly's MethodWriter is way too slow
3. It is not possible to create single code base to generate IL for both (Saving Assembly and creating DynamicMethod), as both have different initialization sequence. DynamicMethod can attach to an existing object and use it as `this`, where else in Assembly, you have to create a class that derives from `ArrayClosure` or similar to support this.

Final conclusion is, 

**If the code has too many branches, JIT will work faster as it will not create native code for branches, and you can create Expression trees to avoid all branches being generated. For example, nested lambda must be converted to IL only if they are going to be executed.**

**Comment by dadhi** [comment]
> If the code has too many branches, JIT will work faster as it will not create native code for unvisited methods, and you can create Expression trees to avoid all branches being generated. For example, nested lambda must be converted to IL only if they are going to be executed.

That's a great point! Currently I am doing eager compilation and looking at other alternatives, e.g. batching compilation together or inlining the lambda code in cirtain cases.
