### ISSUE TITLE
Failing Expressions in Linq2DB

### ISSUE THREAD

**Issue by jogibear9988** [dadhi/FastExpressionCompiler#274]
AccessViolationException:

	var p = new ParameterExpression[10]; // the parameter expressions 
	var e = new Expression[30]; // the unique expressions 
	var l = new LabelTarget[0]; // the labels 
	var expr = Lambda( // $
	  typeof(System.Func<LinqToDB.Linq.IQueryRunner, System.Data.IDataReader, <>f__AnonymousType142<System.Nullable<int>>>),
	  e[0]=Invoke(
		e[1]=Lambda( // $
		  typeof(System.Func<LinqToDB.Linq.IQueryRunner, LinqToDB.IDataContext, System.Data.IDataReader, System.Linq.Expressions.Expression, object[], object[], <>f__AnonymousType142<System.Nullable<int>>>),
		  e[2]=Block(
			typeof(<>f__AnonymousType142<System.Nullable<int>>),
			new[] {
			p[0]=Parameter(typeof(System.Data.SQLite.SQLiteDataReader), "ldr"),
			p[1]=Parameter(typeof(<>f__AnonymousType142<System.Nullable<int>>))
			},
			e[3]=MakeBinary(ExpressionType.Assign,
			  p[0 // (System.Data.SQLite.SQLiteDataReader ldr)
				],
			  e[4]=Convert(
				p[2]=Parameter(typeof(System.Data.IDataReader), "dr"),
				typeof(System.Data.SQLite.SQLiteDataReader))),
			e[5]=MakeBinary(ExpressionType.Assign,
			  p[1 // (<>f__AnonymousType142<System.Nullable<int>> __f__AnonymousType142_Nullable_int____12662012)
				],
			  e[6]=New(/*1 args*/
				typeof(<>f__AnonymousType142<System.Nullable<int>>).GetTypeInfo().DeclaredConstructors.ToArray()[0],
				e[7]=Condition(
				  e[8]=MakeBinary(ExpressionType.NotEqual,
					e[9]=Condition(
					  e[10]=Call(
						p[0 // (System.Data.SQLite.SQLiteDataReader ldr)
						  ], 
						typeof(System.Data.IDataRecord).GetMethods().Single(x => !x.IsGenericMethod && x.Name == "IsDBNull" && x.GetParameters().Select(y => y.ParameterType).SequenceEqual(new[] { typeof(int) })),
						e[11]=Constant((int)0)),
					  e[12]=Constant(null, typeof(System.Nullable<int>)),
					  e[13]=New(/*1 args*/
						typeof(System.Nullable<int>).GetTypeInfo().DeclaredConstructors.ToArray()[0],
						e[14]=Call(
						  p[0 // (System.Data.SQLite.SQLiteDataReader ldr)
							], 
						  typeof(System.Data.IDataRecord).GetMethods().Single(x => !x.IsGenericMethod && x.Name == "GetInt32" && x.GetParameters().Select(y => y.ParameterType).SequenceEqual(new[] { typeof(int) })),
						  e[15]=Constant((int)0))),
					  typeof(System.Nullable<int>)),
					e[16]=Constant(null, typeof(System.Nullable<int>))),
				  e[17]=Condition(
					e[18]=Call(
					  p[0 // (System.Data.SQLite.SQLiteDataReader ldr)
						], 
					  typeof(System.Data.IDataRecord).GetMethods().Single(x => !x.IsGenericMethod && x.Name == "IsDBNull" && x.GetParameters().Select(y => y.ParameterType).SequenceEqual(new[] { typeof(int) })),
					  e[19]=Constant((int)0)),
					e[20]=Constant(null, typeof(System.Nullable<int>)),
					e[21]=New(/*1 args*/
					  typeof(System.Nullable<int>).GetTypeInfo().DeclaredConstructors.ToArray()[0],
					  e[22]=Call(
						p[0 // (System.Data.SQLite.SQLiteDataReader ldr)
						  ], 
						typeof(System.Data.IDataRecord).GetMethods().Single(x => !x.IsGenericMethod && x.Name == "GetInt32" && x.GetParameters().Select(y => y.ParameterType).SequenceEqual(new[] { typeof(int) })),
						e[23]=Constant((int)0))),
					typeof(System.Nullable<int>)),
				  e[24]=Convert(
					e[25]=Constant((int)100),
					typeof(System.Nullable<int>)),
				  typeof(System.Nullable<int>)))),
			p[1 // (<>f__AnonymousType142<System.Nullable<int>> __f__AnonymousType142_Nullable_int____12662012)
			  ]),
		  p[3]=Parameter(typeof(LinqToDB.Linq.IQueryRunner), "qr"),
		  p[4]=Parameter(typeof(LinqToDB.IDataContext), "dctx"),
		  p[5]=Parameter(typeof(System.Data.IDataReader), "rd"),
		  p[6]=Parameter(typeof(System.Linq.Expressions.Expression), "expr"),
		  p[7]=Parameter(typeof(object[]), "ps"),
		  p[8]=Parameter(typeof(object[]), "preamble")),
		p[9]=Parameter(typeof(LinqToDB.Linq.IQueryRunner), "qr"),
		e[26]=Property(
		  p[9 // (LinqToDB.Linq.IQueryRunner qr)
			],
		  typeof(LinqToDB.Linq.IQueryRunner).GetTypeInfo().GetDeclaredProperty("DataContext")),
		p[2 // (System.Data.IDataReader dr)
		  ],
		e[27]=Property(
		  p[9 // (LinqToDB.Linq.IQueryRunner qr)
			],
		  typeof(LinqToDB.Linq.IQueryRunner).GetTypeInfo().GetDeclaredProperty("Expression")),
		e[28]=Property(
		  p[9 // (LinqToDB.Linq.IQueryRunner qr)
			],
		  typeof(LinqToDB.Linq.IQueryRunner).GetTypeInfo().GetDeclaredProperty("Parameters")),
		e[29]=Property(
		  p[9 // (LinqToDB.Linq.IQueryRunner qr)
			],
		  typeof(LinqToDB.Linq.IQueryRunner).GetTypeInfo().GetDeclaredProperty("Preambles"))),
	  p[9 // (LinqToDB.Linq.IQueryRunner qr)
		],
	  p[2 // (System.Data.IDataReader dr)
		]);

run from here:
https://github.com/linq2db/linq2db/blob/bd9b1c922a4cbe3396adaa352c5d9f2df56036aa/Source/LinqToDB/Linq/QueryRunner.cs#L79

**Comment by dadhi** [comment]
@jogibear9988 Great, challenge accepted.

**Comment by jogibear9988** [comment]
Think the second one is easier, but printer does not work for it, see issue #275

**Comment by jogibear9988** [comment]
du you also have a slack space for this?

**Comment by dadhi** [comment]
Nope, let's stay in GH for now. I will look into both issues Tomorrow morning. Maybe will fork the LinqToDb and try to run the tests myself.. will ask you for the help if stuck.

**Comment by jogibear9988** [comment]
System.ExecutionEngineException

	var p = new ParameterExpression[1]; // the parameter expressions 
	var e = new Expression[13]; // the unique expressions 
	var l = new LabelTarget[0]; // the labels 
	var expr = Lambda( // $
	  typeof(System.Func<System.Nullable<Tests.Common.ConvertTests.Enum15>, System.Nullable<int>>),
	  e[0]=Condition(
		e[1]=Property(
		  p[0]=Parameter(typeof(System.Nullable<Tests.Common.ConvertTests.Enum15>), "p"),
		  typeof(System.Nullable<Tests.Common.ConvertTests.Enum15>).GetTypeInfo().GetDeclaredProperty("HasValue")),
		e[2]=Switch(
		  e[3]=Convert(
			p[0 // (System.Nullable<Tests.Common.ConvertTests.Enum15> p)
			  ],
			typeof(Tests.Common.ConvertTests.Enum15)),
		  e[4]=Convert(
			e[5]=Call(
			  null, 
			  typeof(LinqToDB.Common.ConvertBuilder).GetMethods(BindingFlags.NonPublic|BindingFlags.Static).Single(x => !x.IsGenericMethod && x.Name == "ConvertDefault" && x.GetParameters().Select(y => y.ParameterType).SequenceEqual(new[] { typeof(object), typeof(System.Type) })),
			  e[6]=Convert(
				e[3 // Convert of Tests.Common.ConvertTests.Enum15
				  ],
				typeof(object)),
			  e[7]=Constant(typeof(System.Nullable<int>))),
			typeof(System.Nullable<int>)),
		  SwitchCase(
		  e[8]=Constant((int)10, typeof(System.Nullable<int>)),
		  e[9]=Constant(Tests.Common.ConvertTests.Enum15.AA)),
		  SwitchCase(
		  e[10]=Constant((int)20, typeof(System.Nullable<int>)),
		  e[11]=Constant(Tests.Common.ConvertTests.Enum15.BB))),
		e[12]=Constant(null, typeof(System.Nullable<int>)),
		typeof(System.Nullable<int>)),
	  p[0 // (System.Nullable<Tests.Common.ConvertTests.Enum15> p)
		]);

run from here:
https://github.com/linq2db/linq2db/blob/bd9b1c922a4cbe3396adaa352c5d9f2df56036aa/Tests/Linq/Common/ConvertTests.cs#L464

**Comment by jogibear9988** [comment]
NullReferenceException
Test is GroupByAggregate("Northwind.SQLite")

	var p = new ParameterExpression[9]; // the parameter expressions 
	var e = new Expression[23]; // the unique expressions 
	var l = new LabelTarget[0]; // the labels 
	var expr = Lambda( // $
	  typeof(System.Func<LinqToDB.Linq.IQueryRunner, System.Data.IDataReader, System.Linq.IGrouping<bool, Tests.Model.Northwind.Customer>>),
	  e[0]=Invoke(
		e[1]=Lambda( // $
		  typeof(System.Func<LinqToDB.Linq.IQueryRunner, LinqToDB.IDataContext, System.Data.IDataReader, System.Linq.Expressions.Expression, object[], object[], System.Linq.IGrouping<bool, Tests.Model.Northwind.Customer>>),
		  e[2]=Block(
			typeof(System.Linq.IGrouping<bool, Tests.Model.Northwind.Customer>),
			new[] {
			p[0]=Parameter(typeof(System.Data.SQLite.SQLiteDataReader), "ldr")
			},
			e[3]=MakeBinary(ExpressionType.Assign,
			  p[0 // (System.Data.SQLite.SQLiteDataReader ldr)
				],
			  e[4]=Convert(
				p[1]=Parameter(typeof(System.Data.IDataReader), "dr"),
				typeof(System.Data.SQLite.SQLiteDataReader))),
			e[5]=Call(
			  null, 
			  typeof(LinqToDB.Linq.Builder.GroupByBuilder.GroupByContext.GroupByHelper<bool, Tests.Model.Northwind.Customer, LinqToDB.Linq.Builder.ExpressionBuilder.GroupSubQuery<bool, Tests.Model.Northwind.Customer>>).GetMethods(BindingFlags.NonPublic|BindingFlags.Static).Single(x => !x.IsGenericMethod && x.Name == "GetGrouping" && x.GetParameters().Select(y => y.ParameterType).SequenceEqual(new[] { typeof(LinqToDB.Linq.IQueryRunner), typeof(LinqToDB.IDataContext), typeof(System.Data.IDataReader), typeof(System.Collections.Generic.List<LinqToDB.Linq.ParameterAccessor>), typeof(System.Linq.Expressions.Expression), typeof(object[]), typeof(System.Func<LinqToDB.Linq.IQueryRunner, LinqToDB.IDataContext, System.Data.IDataReader, System.Linq.Expressions.Expression, object[], bool>), typeof(System.Func<LinqToDB.IDataContext, bool, object[], System.Linq.IQueryable<Tests.Model.Northwind.Customer>>) })),
			  p[2]=Parameter(typeof(LinqToDB.Linq.IQueryRunner), "qr"),
			  p[3]=Parameter(typeof(LinqToDB.IDataContext), "dctx"),
			  p[4]=Parameter(typeof(System.Data.IDataReader), "rd"),
			  e[6]=Constant(new LinqToDB.Linq.ParameterAccessor[]{}),
			  p[5]=Parameter(typeof(System.Linq.Expressions.Expression), "expr"),
			  p[6]=Parameter(typeof(object[]), "ps"),
			  e[7]=Lambda( // $
				typeof(System.Func<LinqToDB.Linq.IQueryRunner, LinqToDB.IDataContext, System.Data.IDataReader, System.Linq.Expressions.Expression, object[], bool>),
				e[8]=Condition(
				  e[9]=Call(
					p[0 // (System.Data.SQLite.SQLiteDataReader ldr)
					  ], 
					typeof(System.Data.IDataRecord).GetMethods().Single(x => !x.IsGenericMethod && x.Name == "IsDBNull" && x.GetParameters().Select(y => y.ParameterType).SequenceEqual(new[] { typeof(int) })),
					e[10]=Constant((int)0)),
				  e[11]=Constant(false),
				  e[12]=Convert(
					e[13]=Call(
					  null, 
					  typeof(LinqToDB.Common.ConvertBuilder).GetMethods(BindingFlags.NonPublic|BindingFlags.Static).Single(x => !x.IsGenericMethod && x.Name == "ConvertDefault" && x.GetParameters().Select(y => y.ParameterType).SequenceEqual(new[] { typeof(object), typeof(System.Type) })),
					  e[14]=Convert(
						e[15]=Call(
						  p[0 // (System.Data.SQLite.SQLiteDataReader ldr)
							], 
						  typeof(System.Data.IDataRecord).GetMethods().Single(x => !x.IsGenericMethod && x.Name == "GetInt64" && x.GetParameters().Select(y => y.ParameterType).SequenceEqual(new[] { typeof(int) })),
						  e[16]=Constant((int)0)),
						typeof(object)),
					  e[17]=Constant(typeof(bool))),
					typeof(bool)),
				  typeof(bool)),
				p[2 // (LinqToDB.Linq.IQueryRunner qr)
				  ],
				p[3 // (LinqToDB.IDataContext dctx)
				  ],
				p[4 // (System.Data.IDataReader rd)
				  ],
				p[5 // (System.Linq.Expressions.Expression expr)
				  ],
				p[6 // (object[] ps)
				  ]),
			  e[18]=Constant(default(System.Func<LinqToDB.IDataContext, bool, object[], System.Linq.IQueryable<Tests.Model.Northwind.Customer>>)))),
		  p[2 // (LinqToDB.Linq.IQueryRunner qr)
			],
		  p[3 // (LinqToDB.IDataContext dctx)
			],
		  p[4 // (System.Data.IDataReader rd)
			],
		  p[5 // (System.Linq.Expressions.Expression expr)
			],
		  p[6 // (object[] ps)
			],
		  p[7]=Parameter(typeof(object[]), "preamble")),
		p[8]=Parameter(typeof(LinqToDB.Linq.IQueryRunner), "qr"),
		e[19]=Property(
		  p[8 // (LinqToDB.Linq.IQueryRunner qr)
			],
		  typeof(LinqToDB.Linq.IQueryRunner).GetTypeInfo().GetDeclaredProperty("DataContext")),
		p[1 // (System.Data.IDataReader dr)
		  ],
		e[20]=Property(
		  p[8 // (LinqToDB.Linq.IQueryRunner qr)
			],
		  typeof(LinqToDB.Linq.IQueryRunner).GetTypeInfo().GetDeclaredProperty("Expression")),
		e[21]=Property(
		  p[8 // (LinqToDB.Linq.IQueryRunner qr)
			],
		  typeof(LinqToDB.Linq.IQueryRunner).GetTypeInfo().GetDeclaredProperty("Parameters")),
		e[22]=Property(
		  p[8 // (LinqToDB.Linq.IQueryRunner qr)
			],
		  typeof(LinqToDB.Linq.IQueryRunner).GetTypeInfo().GetDeclaredProperty("Preambles"))),
	  p[8 // (LinqToDB.Linq.IQueryRunner qr)
		],
	  p[1 // (System.Data.IDataReader dr)
		]);

https://github.com/linq2db/linq2db/blob/bd9b1c922a4cbe3396adaa352c5d9f2df56036aa/Source/LinqToDB/Linq/QueryRunner.cs#L79

**Comment by jogibear9988** [comment]
System.InvalidCastException: 'Das Objekt des Typs "System.Action`1[System.String]" kann nicht in Typ "Tests.TypeMapping.Dynamic.SimpleDelegate" umgewandelt werden.'

Test is MappingTests.TesCollection()

	var p = new ParameterExpression[2]; // the parameter expressions 
	var e = new Expression[6]; // the unique expressions 
	var l = new LabelTarget[0]; // the labels 
	var expr = Lambda( // $
	  typeof(System.Func<object, object>),
	  e[0]=Block(
		typeof(Tests.TypeMapping.Wrappers.SampleClass),
		new[] {
		p[0]=Parameter(typeof(Tests.TypeMapping.Wrappers.SampleClass))
		},
		e[1]=MakeBinary(ExpressionType.Assign,
		  p[0 // (Tests.TypeMapping.Wrappers.SampleClass SampleClass__14492072)
			],
		  e[2]=New(/*2 args*/
			typeof(Tests.TypeMapping.Wrappers.SampleClass).GetTypeInfo().DeclaredConstructors.ToArray()[0],
			p[1]=Parameter(typeof(object)),
			e[3]=Constant(new System.Delegate[]{default(System.Func<Tests.TypeMapping.Wrappers.SampleClass, int>), default(System.Func<Tests.TypeMapping.Wrappers.SampleClass, int>), default(System.Func<Tests.TypeMapping.Wrappers.SampleClass, int, Tests.TypeMapping.Wrappers.OtherClass>), default(System.Action<Tests.TypeMapping.Wrappers.SampleClass>), default(System.Func<Tests.TypeMapping.Wrappers.SampleClass, int, Tests.TypeMapping.Wrappers.RegularEnum1>), default(System.Func<Tests.TypeMapping.Wrappers.SampleClass, int, Tests.TypeMapping.Wrappers.FlagsEnum>), default(System.Func<Tests.TypeMapping.Wrappers.SampleClass, Tests.TypeMapping.Wrappers.RegularEnum1, int>), default(System.Func<Tests.TypeMapping.Wrappers.SampleClass, Tests.TypeMapping.Wrappers.FlagsEnum, int>), default(System.Func<Tests.TypeMapping.Wrappers.SampleClass, Tests.TypeMapping.Wrappers.RegularEnum1>), default(System.Func<Tests.TypeMapping.Wrappers.SampleClass, Tests.TypeMapping.Wrappers.FlagsEnum>), default(System.Action<Tests.TypeMapping.Wrappers.SampleClass, bool>), default(System.Action<Tests.TypeMapping.Wrappers.SampleClass, Tests.TypeMapping.Wrappers.RegularEnum1>), default(System.Action<Tests.TypeMapping.Wrappers.SampleClass, Tests.TypeMapping.Wrappers.FlagsEnum>), default(System.Func<Tests.TypeMapping.Wrappers.SampleClass, int, Tests.TypeMapping.Wrappers.RegularEnum2>), default(System.Func<Tests.TypeMapping.Wrappers.SampleClass, Tests.TypeMapping.Wrappers.RegularEnum2, int>), default(System.Func<Tests.TypeMapping.Wrappers.SampleClass, Tests.TypeMapping.Wrappers.RegularEnum2>), default(System.Action<Tests.TypeMapping.Wrappers.SampleClass, Tests.TypeMapping.Wrappers.RegularEnum2>), default(System.Func<Tests.TypeMapping.Wrappers.SampleClass, string, string>), null, default(System.Func<Tests.TypeMapping.Wrappers.SampleClass, string, int>)}))),
		e[4]=Invoke(
		  e[5]=Constant(default(System.Action<Tests.TypeMapping.Wrappers.SampleClass>)),
		  p[0 // (Tests.TypeMapping.Wrappers.SampleClass SampleClass__14492072)
			]),
		p[0 // (Tests.TypeMapping.Wrappers.SampleClass SampleClass__14492072)
		  ]),
	  p[1 // (object object__42147750)
		]);

https://github.com/linq2db/linq2db/blob/bd9b1c922a4cbe3396adaa352c5d9f2df56036aa/Source/LinqToDB/Expressions/TypeMapper/TypeMapper.cs#L1149

**Comment by jogibear9988** [comment]
@dadhi 
also could we beautify this lines:

      p[9 // (LinqToDB.Linq.IQueryRunner qr)
		],

like this:

      p[9], // (LinqToDB.Linq.IQueryRunner qr)

**Comment by dadhi** [comment]
> also could we beautify this lines:

Hardly no, because it is requires the expression is parameter check all over the place. I consider it a small price to pay in exchange of simple code in one place.

**Comment by dadhi** [comment]
@jogibear9988 I've fixed a couple of annoying things in the v3-preview-04, hope it unblocks faster test extraction.

Will look into the actual tests later.

**Comment by jogibear9988** [comment]
@dadhi could you reproduce the errors in tests?

**Comment by dadhi** [comment]
@jogibear9988 not yet… was occupied with something else

**Comment by dadhi** [comment]
@jogibear9988 Hello,

I have published the V3-preview-05 with the fixes for the provided expressions and a couple of more things that can improve the LinqToDb picture: nested lambda now can include up to 10 args instead of maximum 6 as before, fix for #281, invocation inlining. Plus the DelegateDebugInfo and multiple fixes for the Expression and C# output.

I would close this issue, so please provide any new findings in the separate one.

**Comment by jogibear9988** [comment]
I've updated the dll in the branch and started the tests...

**Comment by jogibear9988** [comment]
thx
