### ISSUE TITLE
Null Reference Exception in Expression Printer

### ISSUE THREAD

**Issue by jogibear9988** [dadhi/FastExpressionCompiler#275]
![image](https://user-images.githubusercontent.com/364896/97911115-0f37cd00-1d4b-11eb-850d-5fb3c256e991.png)

**Comment by jogibear9988** [comment]
One Step back in Callstack:
![image](https://user-images.githubusercontent.com/364896/97911199-2aa2d800-1d4b-11eb-8cd7-0fb363b97096.png)

**Comment by jogibear9988** [comment]
Switch look's like this in debug view:

	.Switch ($p) {
	.Case (.Constant<Tests.Common.ConvertTests+Enum4>(Value1)):
			15
	.Case (.Constant<Tests.Common.ConvertTests+Enum4>(Value2)):
			25
	.Case (.Constant<Tests.Common.ConvertTests+Enum4>(Value3)):
			0
	.Default:
			(System.Int32).Call LinqToDB.Common.ConvertBuilder.ConvertDefault(
				(System.Object)$p,
				.Constant<System.RuntimeType>(System.Int32))
	}

**Comment by jogibear9988** [comment]
x.Comparison is null

**Comment by jogibear9988** [comment]
Empty Comparison is valid: 
https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.switchexpression.comparison?view=netcore-3.1

**Comment by dadhi** [comment]
Yep, will fix. Thanks again.

**Comment by dadhi** [comment]
@jogibear9988 Fixed in the v3-preview-04
