### ISSUE TITLE
Add a flags to the CompileFast to configure the Invocated Lambda inlining

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#277]
Related #274 

Currently (in v3 preview) the lambda is Not inlined which differs from the System Compile behavior.
In v2 it was inlined.

So the Inlining should be the default behavior and the Prevent Inlining shoud be the opt-in.

Inlining prevention is required when you have multiple the same nested lambdas invocations - so that the nested lambda will be compiled once and reused.

**Comment by jogibear9988** [comment]
Is this relevant for the linq2db tests? Do I need to rerun them with the flag set?

**Comment by dadhi** [comment]
@jogibear9988 No, let me confirm something.. and I did not yet finished the flags impl.
