### ISSUE TITLE
Support .Net 5 or .Net Core?

### ISSUE THREAD

**Issue by lostincomputer** [dadhi/FastExpressionCompiler#282]
Is there a plan to support .Net 5 and/or .Net Core?

**Comment by dadhi** [comment]
FEC supports .NET Standard 2.0, so this should cover both.. 

The tests now are running on Linux and MacOS using .NET Core 3.1. Will upgrade to .NET 5 when CI will support it. Plus I probably need to rerun the benchmarks on .NET 5.. may be something improved, but I did bot heard that they touch the Expressions (we"ll see).

**Comment by dadhi** [comment]
@lostincomputer 

I have updated the benchmarks on the readme to the .NET 5.0
The results did not change (with the slight variation in perf and memory here and there).
