### ISSUE TITLE
Invalid Program after Coalesce

### ISSUE THREAD

**Issue by ackava** [dadhi/FastExpressionCompiler#284]
# Sample C# Code
```c#
        public class Variable
        {

            public string Name { get; set; }
            public Variable(string name)
            {
                Name = name;
            }
        }

    Func<Variable, string, Variable> fx  = (input, text) => {
         input = input ?? new Variable("default");
         input.Value = text;
        return input;
    };
```
# Test Case

```c#

        public class Variable
        {

            public string Name { get; set; }
            public Variable(string name)
            {
                Name = name;
            }
        }


        [Test]
        public void CoalescFail()
        {
            var input = Parameter(typeof(Variable));
            var text = Parameter(typeof(string));
            var ctor = typeof(Variable).GetConstructor(new Type[] { typeof(string) });
            var property = typeof(Variable).GetProperty(nameof(Variable.Name));

            var lambda = Lambda(
                Block(
                Coalesce(input, New(ctor, Constant("default"))),
                Assign(Property(input, property), text),
                input), input, text);

            var t = lambda.ToExpressionString();

            var fx = lambda.CompileFast<Func<Variable, string,Variable>>();

            Assert.NotNull(fx(null,  "a"));
        }
```

It seems any statement after coalesc is failing.

If you look at this link, coalesc is done without loading `null` on to the stack. This could be improvement.

https://sharplab.io/#v2:C4LglgNgPgAgTARgLACgYGYAE9MGFMDeqmJ2WMALJgLIAUAlIcaQL7MntnYIBs3ADHgD2AQwgBTAM4BjWjASCwAOwAOAV2AAaAZgAmI4CMZEUpM9gDsmZeuCYA/Pb0GRDpwCIR7gNyc2p0lR/VCA

**Comment by dadhi** [comment]
Thanks for posting, will check.

**Comment by dadhi** [comment]
@ackava 

Hi again, the expression is wrong in the sense you are not assigning the result of `Coalesce`. 
Both System and Fast Compile are failing with the NullRefEx. 

I have changed the Expression and everything is fine, check the test https://github.com/dadhi/FastExpressionCompiler/blob/0cb6229f46a8af6c5f7358a78b3e260b605b3cc9/test/FastExpressionCompiler.IssueTests/Issue284_Invalid_Program_after_Coalesce.cs#L34

You may also do `expr.PrintCSharp();` in your test and quickly see if the expression is OK.

**Comment by ackava** [comment]
@dadhi Sorry in this test case I have forgotten, but I have a large library in which I am assigning result of Coalesc, but it is still failing, but Linq Expression isn't failing. I will try to isolate the case where it is working in Linq and failing in Fast.

**Comment by dadhi** [comment]
@ackava You may also try to replace Coalesce with Conditional and see if the results change.. I mean, the bug may be in one but not in another.

**Comment by ackava** [comment]
@dadhi 

I think I found root cause, problem is due to `New` expression after Coalesce. .

Try this code,

First try commenting `CompileSys` it will result in Invalid program runtime. But if you uncomment `CompileSys`, it will 

```c#
            var input = Parameter(typeof(Variable));
            var text = Parameter(typeof(string));
            var ctor = typeof(Variable).GetConstructor(new Type[] { typeof(string) });
            var property = typeof(Variable).GetProperty(nameof(Variable.Name));

            var lambda = Lambda(
                Block(
                Coalesce(input, New(ctor, Constant("default"))),
                Assign(Property(input, property), text),
                input), input, text);

            // var t = lambda.ToExpressionString();

            var fx2 = lambda.CompileSys();
            Assert.Throws(typeof(System.Reflection.TargetInvocationException), () =>
             fx2.DynamicInvoke(null, "a"));


            var fx = lambda.CompileFast<Func<Variable, string, Variable>>();

            Assert.Throws(typeof(System.Reflection.TargetInvocationException), () =>
             fx(null, "a"));
```

I know the expression is wrong, but `CompileSys` successfully throws `NullReferenceException`, but `CompileFast` results in `Invalid runtime`. 

The point here is, generated IL corrupts some state, instead of throwing exception.

**Comment by dadhi** [comment]
@ackava Good, I will look.

**Comment by dadhi** [comment]
Happy birthday this issue. I will look into you. I promise and happy NY!

**Comment by ackava** [comment]
@dadhi Thanks for update, I was unable to use your library to save il to assembly (it requires lot of work as building types and mapping delegates). We wanted to use it to generate IL for JavaScript engine we were writing. So we recreated Expression Library with little different approach then the one you took. It is available at 

https://www.webatoms.in/blog/yantra-js/Yantra-Expression-Compiler-for-DotNet-2j#contextId=3

Please have a look at it and if there is anyway I can contribute, I am open for help.

**Comment by dadhi** [comment]
@ackava Wah, thanks for sharing. Will check to learn something.
