### ISSUE TITLE
Design Question

### ISSUE THREAD

**Issue by ackava** [dadhi/FastExpressionCompiler#286]
I looked at how the code is organized in FEC, 

Why didn't you consider changing expression tree first to incorporate closure collection in the transformed Expression Tree. I think debugging would be easier as you can visualize both expressions.

The code generation part can simply translate expression. This phase can throw exception stating no variable/parameter found in scope. Code generation phase can also simply compare LINQ and FEC as  both will be identical.

In this case, user can directly use phase 2 if they are confident that they do not have any closures.

**Comment by dadhi** [comment]
> Why didn't you consider changing expression tree first to incorporate closure collection in the transformed Expression Tree.

How?

> In this case, user can directly use phase 2 if they are confident that they do not have any closures.

The first phase does a bit more: sroring the block (scope) variables hierarchy and discovers the label targets.

**Comment by ackava** [comment]
Phase 1

Lets say one want to create following expression.
```c#
    Func<int, Func<int>> add = (n) => (m) => n + m;
```
First phase will change lambda from.. `n => m => n + m` , `n` is closure in nested lambda, it will change it to...
```c#
    n => (new ClosureFunction<int>(new object[] {n}, (c, m) => (int)c[0] + m).Delegate;
```
I have simplified this expression just for display.

```c#
class ClosureFunction<T> {
    delegate T Function(object[] closures);
    public readonly Func<T> Delegate;
    ClosureFunction(object[] closures, Function fx) {
         Delegate  = () => fx(closures);    
    }
}
```

Now second expression is absolutely free of closure (constants, variables). While in this phase, it can detect label targets and store it in the expression, you already have FEC expressions, you can have internal hidden fields to store more information.

Second phase generator would be simpler in design as it would not need to worry about any closure, it would simply generate the code and if it finds variable/parameter not in current function arguments/variables, it would just throw saying Variable not found.

**Comment by dadhi** [comment]
@ackava Thanks for the idea.

- This rewrite is the complex one, and from the gist of it I am not sure about the corner cases. 
- It will also increase the memory producing the new expressions.
- Not sure how to deal with the same instances of the nested lambda expressions (may be on the different levels).
- Having the additional fields in light expression won't work for the system expression. But if I took this road - it increases the memory spent, but more importantly the internal expression may be part of the multiple lambda expression thus dealing with the mutable shared state.

Anyway, I am welcoming any idea or the different view on my current implementation to improve things. So you may try the prototype or something, but I would not guatantee to merge it.

There are already the more specific issues open with ideas for improvement, so you may have a look into them. A smaller improvement has more chances to fly considering the FEC topic complexity.

**Comment by ackava** [comment]
> This rewrite is the complex one, and from the gist of it I am not sure about the corner cases.

Agree, but I feel it will be easier to separate in two different classes to reduce complexity. As we tend to add more features, separation will make it easy to extend FEC parallelly in both phases.

> How is the performance of Compiling and moreover the Invoking the result delegate compares to the current approach.
It will also increase the memory producing the new expressions.

Wouldn't be exactly same? For simplicity I displayed a class, but you can use `Curry` functions in first phase instead of `ClosureFunction`.

```c#
 n => CurryClosureFuncs.Curry<object[],int>(new object[] {n}, (c, m) => (int)c[0] + m));
```

> The rewrite still requires the additional traversal anyway with the similar bound constant search and nested lambdas processing

Reducing traversal is not the aim here. Again we can change the expressions in such a way to avoid doing these things in 2nd phase.

>Not sure how to deal with the same instances of the nested lambda expressions (may be on the different levels).

I guess whatever is done at 2nd phase can be simplified in first phase and if we encounter same syntax of inner lambda, it can be reused.

> Having the additional fields in light expression won't work for the system expression. But if I took this road - it increases the memory spent, but more importantly the internal expression may be part of the multiple lambda expression thus dealing with the mutable shared state.

Yes it is a bit of problem. But what if we ditch System Expression in 2nd phase, Expressions built with System Expression or FEC both go through Phase 1 that produces FEC expression, which can be visualized, cached, more features we can think of we can add.

Think of supporting `yield,lock,await` etc in future, though it is far fetched, but someone can write expression translator from system to FEC and such features can be added. Currently System expression is locked and we have no control over it.

**Comment by dadhi** [comment]
> Complexity - Agree, but I feel it will be easier to separate in two different classes to reduce complexity.
> Performance - Wouldn't be exactly same?
> Reducing traversal is not the aim here. Again we can change the expressions in such a way to avoid doing these things in 2nd phase.

Then I am not sure what is the win :/
