### ISSUE TITLE
Referencing FEC Source directly

### ISSUE THREAD

**Issue by jogibear9988** [dadhi/FastExpressionCompiler#288]
If I want to reference the FEC Source directly, I would not expose the FEC Types.

Do you have a good strategy hwo to make all the Types internal?

Will there also be a nuget for the source inclusion, with internal types?

**Comment by dadhi** [comment]
Yes, here https://www.nuget.org/packages/FastExpressionCompiler.Internal.src/3.0.0-preview-04

But I did not release the latest previews with it. Will do if you need though.

**Comment by jogibear9988** [comment]
No, I'm currently workin on my own serializer where I will use your lib.

**Comment by dadhi** [comment]
Good, I've just released the latest fixes and changes with the v3-preview-07 including the FEC.internal.src package.
