### ISSUE TITLE
Have you considered wrappers around ILGenerator?

### ISSUE THREAD

**Issue by EamonNerbonne** [dadhi/FastExpressionCompiler#3]
So perhaps this is all old-hat to you, but I can imagine that poking around IL is timeconsuming.  Have you considered things like [gremit](https://github.com/skbkontur/gremit) or [sigil](https://github.com/kevin-montrose/Sigil)?

Those might (certainly initially) help you broaden the base of the generated il; and certainly sigil takes care of some really boring IL-related minutiae (such as short vs. long for instructions and so on).

**Comment by dadhi** [comment]
Yeah, I did considered but their use adds overhead. 
Comparisons and logical ops were added lately, and did not check for the all cases.

So will try to fix now.

**Comment by dadhi** [comment]
Those libs are more about safety and not about perf in the first place, at least not about cold start/compilation perf. 

Plus a dependency. 

I think for more bigger lib or app it would be the best to use them.

**Comment by EamonNerbonne** [comment]
Fair enough; I thought I'd mention it.  There's a trade-off here between performance and breadth of expression tree perf - at least assuming it's simpler to use those libraries.  Have you checked the overhead?  Because really superficially, even though compilation *is* 30x faster, the JIT takes just as long, so the total time of compilation+execution has as a lower bound the JIT time.  And that means the best gain you can hope for overall is around 2x (unless you make delegates you don't execute, which is a reasonable use-case, but one with alternatives such as `Lazy<>`).

And you could do some hybrid approach, wherein the really common trivial cases such as "this is just a constructor" or "just a method call" are fast-pathed, but things that are more complicated such as various binary operators, constants, etc. use a slightly slower but simpler sigil path.

In any case, I respect the wish to keep using ILGenerator; the advantages are undeniable.  And extra dependencies can be a pain, sure (although in .net core world this seems to be the new normal, so maybe it'll turn out OK).

**Comment by dadhi** [comment]
.net core is new OK - yeah! 

Mmm, about hybrid approach I will think about it. 

In any case for v1 if I would not make fix for specific feature, I would probably turn it off from compiler. Fallback all the things :-)

**Comment by EamonNerbonne** [comment]
Yeah, makes sense!

**Comment by dadhi** [comment]
Hi @EamonNerbonne , just published v1! Decided that more features may wait for the next versions.

Back to the question. There is an alternative lib [GrobExp.Compiler](https://github.com/skbkontur/GrobExp.Compiler) from [gremit](https://github.com/skbkontur/gremit) with the same goal. I've checked the code, e.g. how constants are emitted, and did not found too many surprises. You still need to do the same housekeeping, probably because the input are expressions, rather then manual emitting.

So closing this question. Happy releasing!
