### ISSUE TITLE
InvalidOperationException in the Mapster

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#301]
System.InvalidProgramException: 'Common Language Runtime detected an invalid program.'

StackTrace

```
   at Mapster.TypeAdapter.Adapt[TSource,TDestination](TSource source) in D:\Dev\Mapster\src\Mapster\TypeAdapter.cs:line 55
   at Benchmark.TestAdaptHelper.ConfigureMapster(Customer customerInstance, MapsterCompilerType type) in D:\Dev\Mapster\src\Benchmark\TestAdaptHelper.cs:line 114
   at Benchmark.Benchmarks.TestComplexTypes.SetupFec() in D:\Dev\Mapster\src\Benchmark\Benchmarks\TestComplexTypes.cs:line 70
   at Benchmark.Program.Main(String[] args) in D:\Dev\Mapster\src\Benchmark\Program.cs:line 22
```

**Comment by CyberBotX** [comment]
I don't think this problem has been fixed, even up to 3.0.4. I just tried the following short snippet in LINQPad using FastExpressionCompiler 3.0.4 and Mapster 7.1.5:

```CSharp
class Test
{
	public string? TestString { get; set; }
}

void Main()
{
	TypeAdapterConfig.GlobalSettings.Compiler = exp => exp.CompileFast();
	_ = TypeAdapterConfig.GlobalSettings.Default.MapToConstructor(true).PreserveReference(true);
	
	var test1 = new Test()
	{
		TestString = "Test"
	}.Dump();
	var test2 = test1.Adapt<Test>().Dump();
}
```

I get an `InvalidProgramException` with the message `Common Language Runtime detected an invalid program.` The stack trace is:

```
   at (ArrayClosure , Object )
   at Mapster.TypeAdapter.Adapt[TDestination](Object source, TypeAdapterConfig config)
   at Mapster.TypeAdapter.Adapt[TDestination](Object source)
   at UserQuery.Main()
```

Please reopen this and look into it. I have had to temporarily exclude using FEC in my programs using Mapster as a result of this.

**Comment by dadhi** [comment]
@CyberBotX I will look into this. Thanks for posting.

**Comment by michalsedlak** [comment]
Hello, I'm facing the same issue with Mapster 7.2. Thank you for fixing that.

**Comment by dadhi** [comment]
@michalsedlak I am working on it right now.

**Comment by dadhi** [comment]
fixed in v3.0.5

**Comment by dadhi** [comment]
@CyberBotX Could you check the Mapster again?

**Comment by CyberBotX** [comment]
I checked earlier today, and the example I provided for LINQPad runs with no exception. :D

**Comment by cojocaru-dragos-alexandru** [comment]
I'm facing the same issue. With the latest version of Mapster and v3.0.5 of FastExpressionCompiler I get a "Common Language Runtime detected an invalid program." error.

Reverting back to v2.0.0 seems to work, however I'd love to see this fixed in the latest version.

**Comment by dadhi** [comment]
@cojocaru-dragos-alexandru

**Comment by dadhi** [comment]
And maybe someone (@chaowlert) know how to run all Mapster tests with FEC?

**Comment by chaowlert** [comment]
Hey, good to join. I created `fec` branch (https://github.com/MapsterMapper/Mapster/tree/fec).
I tested unit tests, 10 cases failed. Most seemed to related to dictionary.

Just wondering, for default usage, Should we expect FEC to fallback to original lambda.Compile or not? In most cases, we could enjoy performance boost. In corner cases, app still working.

**Comment by dadhi** [comment]
@chaowlert Thanks for responding :)
I will check the fork and how is the `CompileFast` called there. It should fallback by default (if no arguments passed).

**Comment by cojocaru-dragos-alexandru** [comment]
> @cojocaru-dragos-alexandru Could you provide the example similar to the one from @CyberBotX

My example would be identical to his, because as I said, I removed all configurations from Mapster and left only this line:

`TypeAdapterConfig.GlobalSettings.Compiler = exp => exp.CompileFast();`

**Comment by dadhi** [comment]
@chaowlert Thanks for responding :)
I will check the fork and how is the `CompileFast` called there. It should fallback by default (if no arguments passed).

**Comment by dadhi** [comment]
Found the cause of Dictionary tests failing - the V3 has added the support for the `ListInit` expression (V2 used the fallback) but there is a bug in emitting the `ElementInit` for the Dictionary. Fixing now.

**Comment by dadhi** [comment]
All Mapster tests are now passing in https://github.com/MapsterMapper/Mapster/tree/fec
and all is compiled using the FEC - no fallback used.
Releasing the v3.1.0...

**Comment by dadhi** [comment]
@chaowlert @CyberBotX @cojocaru-dragos-alexandru FEC v3.1.0 is out

**Comment by cojocaru-dragos-alexandru** [comment]
I'm still getting the following exception:

```bash
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at (ArrayClosure , Object )
   at Mapster.TypeAdapter.Adapt[TDestination](Object source, TypeAdapterConfig config)
   at Mapster.TypeAdapter.Adapt[TDestination](Object source)
```

I'm using FastExpressionCompiler 3.2.0 and Mapster 7.2.0

**Comment by dadhi** [comment]
@cojocaru-dragos-alexandru What is the setup for this error? Could you provide the sample?

**Comment by cojocaru-dragos-alexandru** [comment]
It's a .NetCore5 class library. These are the project dependencies:

		<PackageReference Include="AsyncEnumerator" Version="4.0.2" />
		<PackageReference Include="FastExpressionCompiler" Version="3.2.0" />
		<PackageReference Include="FluentValidation.AspNetCore" Version="10.2.3" />
		<PackageReference Include="Mapster" Version="7.2.0" />
		<PackageReference Include="MassTransit.Azure.ServiceBus.Core" Version="7.2.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.7" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="5.0.0" />
		<PackageReference Include="MassTransit" Version="7.2.1" />
		<PackageReference Include="MassTransit.AspNetCore" Version="7.2.1" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="7.2.1" />
		<PackageReference Include="NEST" Version="7.13.1" />
		<PackageReference Include="SerilogTimings" Version="2.3.0" />

**Comment by dadhi** [comment]
@cojocaru-dragos-alexandru 

I have run the tests from the Mapster with the FEC 3.2 and everything is passing:
![image](https://user-images.githubusercontent.com/39516/124354116-09182a00-dc13-11eb-9493-d0dfb6c37e0b.png)

So it would be hard to impossible to figure out until I have the failing sample/test.

**Comment by dadhi** [comment]
closing

**Comment by Exmirai** [comment]
Issue is still persists in latest version. There's a piece of faulty configuration: 
```
TypeAdapterConfig.GlobalSettings.Compiler = exp => exp.CompileFast();
TypeAdapterConfig.GlobalSettings.Default.PreserveReference(true);
TypeAdapterConfig<JsonObject, JsonObject>.NewConfig()
                .ConstructUsing((src) => src.DeepClone().AsObject());
```

where JsonObject is System.Text.Json.Nodes.JsonObject

**Comment by dadhi** [comment]
@Exmirai v5.0.3 has been released.
