### ISSUE TITLE
InvalidProgramException when Binary(liftToNull: true)

### ISSUE THREAD

**Issue by exyi** [dadhi/FastExpressionCompiler#309]
This expression is compiled successful, but then fails to execute.

```csharp
public void TestCase1()
{
  var expr = Lambda<Func<object>>( //$
    Convert(
      MakeBinary(ExpressionType.GreaterThan,
        Default(typeof(int?)),
        Constant(10, typeof(int?)),
        liftToNull: true, null),
      typeof(object)));
  var f = expr.CompileFast();
  f();
}
```

When liftToNull is false, then it works. Also, the Conversion of bool? to object is important, without it, it works as expected.

**Comment by dadhi** [comment]
@exyi 
Interesting, I believe I did not just account or maybe just skipping the `liftToNull` (don't remember). 
Why do you need this anyway? Is it something prevalent in your code?

Asking, because if I decide just to fallback to the System Compile for the expressions with liftToNull - given the support of them are too complex. Does it hurt your perf then?

**Comment by exyi** [comment]
it's quite prevalent (maybe 10% of the expression will have it), but I can get rid of it quite easily, so feel free to fallback to System Compile if it's easier.

**Comment by dadhi** [comment]
OK, got it.

Seems like I am ignoring it and just make things fail. 
Maybe we'll spend a bit of time to grasp what does it do with help of your test case, and if it is taking too long will fallback.

**Comment by exyi** [comment]
hmm, when looking how System Compile does it, it does not seem too complicated https://source.dot.net/#System.Linq.Expressions/System/Linq/Expressions/Compiler/LambdaCompiler.Binary.cs,383, but I probably can't figure out myself uncertain how to transform this logic to your compiler :|

**Comment by dadhi** [comment]
@exyi Thanks for hint.

**Comment by jogibear9988** [comment]
Here is the source form netcore:
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/Compiler/LambdaCompiler.Binary.cs#L147

It is MIT Licence, https://github.com/dotnet/runtime/blob/main/LICENSE.TXT
