### ISSUE TITLE
InvalidProgramException when nullable result is ignored

### ISSUE THREAD

**Issue by exyi** [dadhi/FastExpressionCompiler#310]
The error occurs when I have a Convert expression returning Nullable<int>, but I ignore the result. For example

```csharp
[Test]
public void Case2_A()
{
  var p = Parameter(typeof(int), "tmp0");
  var expr = 
    Lambda<Action<int>>(Block(
      Convert(p, typeof(int?)),
      Default(typeof(void))), p);

  var f = expr.CompileFast();
  f(2);
}
```

Or similar:

```csharp

[Test]
public void Case2_B()
{
  var p = Parameter(typeof(int), "tmp0");
  var expr = 
    Lambda<Action<int>>(Convert(p, typeof(int?)), new[] { p });
  var f = expr.CompileFast();
  f(2);
}
```

In these simple cases, I could just not place the ignored convert there, but it also fails in more complex cases when the conversion is nested in conditions/blocks, but the result is still not used in the end.

**Comment by dadhi** [comment]
@exyi Great that reproducible samples are small. Will check.

If you're interested, you may look how would I address, test and fix the issues (look at fix for #307 as an example https://github.com/dadhi/FastExpressionCompiler/commit/35b9a8fed3a6d2afdc46813480944d49d7146426) 

In other words, PRs are welcome ;)
