### ISSUE TITLE
`in` parameter

### ISSUE THREAD

**Issue by sebastienros** [dadhi/FastExpressionCompiler#316]
On net6.0 only, with this class

```
    public class ParseException : Exception
    {
        public ParseException(string message, in TextPosition position) : base(message)
        {
            Position = position;
        }

        public TextPosition Position { get; set; }
    }
```

Try to create an instance like this:

```
Expression.Throw(Expression.New(typeof(ParseException).GetConstructors().First(), new [] { Expression.Constant("Message"), context.Position() } ))
```

Fails with a message similar to "invalid CLR ..." when invoking the lambda. Works fine when I remove the `in` marker in the arguments list. Works fine on netcoreapp3.1 and net5.0 in my tests.

**Comment by sebastienros** [comment]
Apart from that, some feedback, got some relatively small expressions compiled from 

```
|                         Method |       Mean |    Error |  StdDev |  Gen 0 |  Gen 1 | Allocated |
|------------------------------- |-----------:|---------:|--------:|-------:|-------:|----------:|
|      CreateCompiledSmallParser | 1,373.9 us | 31.08 us | 1.70 us | 7.8125 | 3.9063 |     50 KB |
| CreateCompiledExpressionParser |   200.1 us | 10.71 us | 0.59 us | 1.4648 | 0.7324 |     10 KB |
```

to 

```
|                         Method |     Mean |     Error |   StdDev |  Gen 0 |  Gen 1 |  Gen 2 | Allocated |
|------------------------------- |---------:|----------:|---------:|-------:|-------:|-------:|----------:|
|      CreateCompiledSmallParser | 75.44 us | 24.697 us | 1.354 us | 5.3711 | 2.6855 | 0.1221 |     33 KB |
| CreateCompiledExpressionParser | 15.45 us |  1.171 us | 0.064 us | 0.8850 | 0.4272 |      - |      6 KB |
```

**Comment by dadhi** [comment]
First probably is an issue but the full test will help or better the PR with test. See the Issue Tests project for examples.

Regarding the benchmarks I need the benchmark code to interpret them. I dont see what are you testing and how.

**Comment by sebastienros** [comment]
Good point about the unit tests, I will create one. Tried my luck in case you already knew the limitation with the `in` modifier.

The benchmarks are just a celebratory comment to show how much improvement I am getting with FEC, just replacing a `Compile()` with `CompileFast()` when used in https://github.com/sebastienros/parlot

**Comment by dadhi** [comment]
> Tried my luck in case you already knew the limitation with the in modifier.

Got it. There were some bugs reported before with `in` but those were fixed.

>  The benchmarks are just a celebratory comment

Great. I am usually adding the ratio and the fec/fast words into the benchmarks to get the results by glance. Here I got it wrong :-)

**Comment by dadhi** [comment]
@sebastienros 
I have added [two tests](test/FastExpressionCompiler.IssueTests/Issue316_in_parameter.cs) based on your problem description.
But I did not get the "Invalid CLR..." exception, instead I get the NRE. 
So I have fixed those in FEC.

If your case is different, please provide the test or PR (in the same file) and reopen the issue.

**Comment by sebastienros** [comment]
I assume you don't publish your master branch on myget (for instance) automatically to test before it's released?

**Comment by dadhi** [comment]
No. Mmm.. I will check some options Tomorrow.

**Comment by dadhi** [comment]
@sebastienros v3.2.2 is on NuGet

**Comment by sebastienros** [comment]
Saw that thank you, and was looking for a sponsor page on GH :/ doesn't work in Belarus?

**Comment by dadhi** [comment]
Honestly did not check. I am in Spain now.. so maybe it works.

**Comment by sebastienros** [comment]
It would definitely work, should be super easy to setup. At least even if you get a cerbeza worth of it you should do it.

**Comment by dadhi** [comment]
@sebastienros Hi, I have setup the Sponsors. GitHub was taking its time to approve, otherwise yes, it was rather simple procedure.

**Comment by dadhi** [comment]
@sebastienros  OMG thanks! :-)
