### ISSUE TITLE
Pass Closures to your ExpressionClasses

### ISSUE THREAD

**Issue by Shpendicus** [dadhi/FastExpressionCompiler#323]
Take a look:

`public CommandBuffer Work(LambdaExpression fastLambdaExpr) { ........ }`

`         CommandBuffer<char> lambda = Work(Expression.Lambda((X) => X + 10));`

I get the error: CS1660: 
https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1660?f1url=%3FappId%3Droslyn%26k%3Dk(CS1660)

Pls help, I wanna really use ur stuff :D

**Comment by Shpendicus** [comment]
Btw: Would be really nice, cause I think that this wont work right now, to allow an explicit conversion from 
`System.Linq.Expressions.Expression`  to `FastExpressionCompiler.LightExpression.Expression`

so that people can use the `(a0, a1) => a0.DoSmthWith(a1)` as a closure BUT pass it to the method who expects a type of:

FastExpressionCompiler.LightExpression.Expression, which will be then converted to your type and then you can use the super fast. expr.CompileFast(lambda) and so on...

**Comment by dadhi** [comment]
Answering here the questions and the one from the #179.

The conversion from the lambda to the Expression is natively supported by the C# compiler. The Roslyn does all the parsing, type checking and creating the expression behind the scene:
```cs
Expression<Func<int, int, int>> foo = (x, y) => x + y;
```

It means we cannot do this conversion directly for our own `LightExpression.Expression` type or any other custom type.
The `LightExpression` is for manually creating the expression:
```cs
using static FastExpressionCompiler.LightExpression.Expression;
var x = Parameter(typeof(int), "x");
vaf y = Parameter(typeof(int), "y");
var foo = Lambda<Func<int, int, int>>(Add(x, y), x, y);
```
The `LightExpression` API is specifically designed in the way to mirror the `Expression` API, so you may migrate from
second to the first just by changing `using static`.

Answering another question, we may in principle convert an already created `Expression` to the `LightExpression.Expression`. 
But it defends the reason for the creation of the light expression. It was created to minimize the memory consumed by the created expression and speed-up the creation. So the main goal is the performance and again the performance.
So when you are converting `Expression` to `LightExpression` you do the work twice.

**Comment by Shpendicus** [comment]
Ok that makes quite abit of sense, yea. 

Hmm the thing is, I really need the user of my codebase to pass any sort of lambda and so I can create an efficient expressiontree from that function/lambda, I mean this here would be also okay if that would be possible.

`   public <FastExpression> Transform(delegate* unmanaged<T, T> funcPtr)
    {
        Func<T, T> myFunc = Marshal.GetDelegateForFunctionPointer<Func<T, T>>((nint)funcPtr);
        <FastExpression>.CreateExpressionFromDelegate(myFunc);
    }    
`

**OR**
public <FastExpression> Transform(Func<T, T> someFunc)
{
     return <FastExpression>.CreateExpressionFromDelegate(someFunc);
}
smth like this...

would this somehow be possible?

**Comment by dadhi** [comment]
@Shpendicus I am not sure if it fit, but you may check this project https://github.com/stakx/DelegateDecompiler

**Comment by Shpendicus** [comment]
@dadhi damn mate, this is exactly wh1at I want and you know what, when my current project is done, I will fork his project and modify it that It also can understand your FastExpressions and THEN also create out of "delegate*<,,,,>" a FastExpression, damn mate were onto smth here, which is hardcore powerful!!

Your project hardcore inspired me, keep up the good work!

**Comment by dadhi** [comment]
cheers!
