### ISSUE TITLE
Update performance tests to .NET 8 

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dadhi/FastExpressionCompiler#332]
.NET 6 and 7 got huge performance boosts.

**Comment by dadhi** [comment]
I will update when the .NET 7 is released. 
Though I did not hear of any Expression related performance work in it.
Maybe you know some?

**Comment by dzmitry-lahoda** [comment]
They improved .NET JIT afaik a lot in .NET 6 and 7, on top of 5. Not expression specific.

Oh, found stuff while googling https://github.com/dotnet/runtime/tree/main/src/libraries/System.Linq.Expressions  - they deprecated kind of expressions...

**Comment by dadhi** [comment]
> deprecated kind of expressions...

Their reasoning is amazing, just means "we don't care". Good for me then.

**Comment by dadhi** [comment]
Don't forget to add the ` Alloc Ratio` column to the benchmarks and **mention it in the readme**.

**Comment by Giorgi** [comment]
Can you update it to .Net 8 once it's released?

**Comment by dadhi** [comment]
@Giorgi Yes, I will.

**Comment by dadhi** [comment]
BMs and readme are updated
