### ISSUE TITLE
NullReferenceException when calling CompileFast() results

### ISSUE THREAD

**Issue by yuretz** [dadhi/FastExpressionCompiler#353]
Trying to run the code
```csharp
var sum = Expression.Parameter(typeof(Func<int, int>));
var i = Expression.Parameter(typeof(int), "i");
var n = Expression.Parameter(typeof(int), "n");

var lambda = Expression.Lambda<Func<int, int>>(
    Expression.Block(
        new[] { sum },
        Expression.Assign(
            sum,
            Expression.Lambda(
                Expression.Condition(
                    Expression.MakeBinary(ExpressionType.Equal, i, Expression.Constant(0)),
                    Expression.Constant(0),
                    Expression.MakeBinary(
                        ExpressionType.Add,
                        i,
                        Expression.Invoke(
                            sum,
                            Expression.MakeBinary(ExpressionType.Subtract, i, Expression.Constant(1))))),
                i)),
        Expression.Invoke(sum, n)),
    n);

var func = lambda.CompileFast();

Console.WriteLine(func(10));
```
gives  `NullReferenceException` with the following stack trace
```
   at (ArrayClosure, Int32)
   at FastExpressionCompiler.ExpressionCompiler.CurryClosureFuncs.<>c__DisplayClass2_0`3.<Curry>b__0(T1 t1)
   at UserQuery.Main()
```

Everything works as expected if I use the standard slow `.Compile()`

I'm using .NET 7.0 with FastExpressionCompiler 3.3.3

Am I doing something wrong? Thanks in advance for your help!

**Comment by dadhi** [comment]
@yuretz 
Hi, thanks for reporting and for the code example. 
I will check.

**Comment by dadhi** [comment]
The problem is the recursive use of delegate and likely its value is not set into closure when assigned.
I have added the failing test and proceed from here.

**Comment by yuretz** [comment]
Exciting! Thank you for the fix! I'm going to try it with my toy lisp implementation and see if FastExpressionCompiler instead of the built-in one. There is a lot of recursion and closures involved, so this would be a good test too 😉

**Comment by dadhi** [comment]
Interesting, keep me posting.
