### ISSUE TITLE
Error with converting to/from signed/unsigned integers

### ISSUE THREAD

**Issue by TYoungSL** [dadhi/FastExpressionCompiler#355]
Given  the following expression;

```csharp
var e = new Expression[6]; // the unique expressions
var expr = Lambda<System.Func<int>>(
  e[0]=Convert(
    e[1]=MakeBinary(ExpressionType.RightShift,
      e[2]=Convert(
        e[3]=Constant(-13),
        typeof(System.UInt32)),
      e[4]=Convert(
        e[5]=Constant((UInt32)1),
        typeof(int))),
    typeof(int)), new ParameterExpression[0]);
```

When using CompileFast, this should evaluate to 0x7ffffff9, but instead evaluates to -7 (0xfffffff9).

When using CompileSys, this works as expected, the result is 0x7ffffff9.

**Comment by TYoungSL** [comment]
Here is a test case to demonstrate the issue, I assume this should go into `ConstantAndConversionTests`
```csharp
[Test(Description = "Unsigned shifts should work")]
public void Unsigned_shifts_should_work()
{
    var x = -1;
    var y = 0x7fffffff;
    Expression<Func<bool>> lambda = () => unchecked((uint)x) >> 1 == y;
    Assert.IsTrue(ExpressionCompiler.CompileSys(lambda)()); // passes
    Assert.IsTrue(ExpressionCompiler.CompileFast(lambda, true)()); // fails
}
```

**Comment by dadhi** [comment]
Thanks for the tests, I will check later.

**Comment by TYoungSL** [comment]
@dadhi what's the deal?

**Comment by TYoungSL** [comment]
https://github.com/dadhi/FastExpressionCompiler/blob/3835ddf8f3ed53182952871de4a596dd361cf9cb/src/FastExpressionCompiler/FastExpressionCompiler.cs#L4804
```csharp
ExpressionType.RightShift => exprType.IsUnsigned() ? OpCodes.Shr_Un : OpCodes.Shr
```

Maybe something like this?

**Comment by dadhi** [comment]
@TYoungSL Thanks for looking yourself :), I did not have the time.
Looking at the PR.
