### ISSUE TITLE
Add RequiresUnreferencedCode attribute to types

### ISSUE THREAD

**Issue by ovska** [dadhi/FastExpressionCompiler#361]
It's my understanding that FastExpressionCompiler by its very nature does not support trimming/NativeAOT. However it could be helpful for libraries that use it as an optional code path for regular scenarios to add  `[RequiresUnreferencedCode]` to the following types:

- `ExpressionCompiler`
- `ExpressionCompiler.EmittingVisitor`
- `ToExpressionPrinter`
- `Tools`

I'm not super knowledgeable about trimming, but I think this should accomplish two things:
1. Make it abundantly clear to callers that the library doesn't work in these scenarios
2. Suppress global trimming warning during compile from this library globally, despite the code paths using FastExpressionCompiler being marked with the required attributes.

I can do the grunt work of applying the attributes and verifying that it resolves the compiler warnings if needed.

**Comment by dadhi** [comment]
Great, go ahead!
