### ISSUE TITLE
Calling a user defined == operator runs into a CLR invalid program exception

### ISSUE THREAD

**Issue by Marluwe** [dadhi/FastExpressionCompiler#394]
First of all: Thank you for this amazing package! 

I found out that there is an issue with user defined == operators. The tested version is the current release 4.1.0 running on .net6.

Here is minimal example. The .net internal compile is fine.
```c#
using System.Linq.Expressions;
using FastExpressionCompiler;
// a lambda using a user defined equals operator
LambdaExpression expressionA = (TestInstance instance) => instance == 5;
var funcA = expressionA.CompileFast();
Console.WriteLine("Compilation OK");
var instanceA = new TestInstance { Value = 5 };
try
{
    Console.WriteLine(funcA.DynamicInvoke(instanceA));
    Console.WriteLine("Calling funcA - OK");
}
catch (Exception e)
{
    Console.WriteLine("Calling funcA => " + e.Message + Environment.NewLine + e.InnerException.Message);
}

public class TestInstance
{
    public int Value;
    public static bool operator ==(TestInstance instance, int value) => instance.Value == value;
    public static bool operator !=(TestInstance instance, int value) => instance.Value != value;
}
```

The output is

> Compilation OK
> Calling funcA => Exception has been thrown by the target of an invocation.
> Common Language Runtime detected an invalid program.

**Comment by Marluwe** [comment]
I assume the issue lies here, as the equality operator needs to check the second parameter type to match the right operand.

<img width="790" alt="image" src="https://github.com/dadhi/FastExpressionCompiler/assets/15705744/554b55be-af2b-407e-b9b0-08d7882185bf">

**Comment by dadhi** [comment]
@Marluwe Thanks for the fix. Coming with the v4.1.1 release.
