### ISSUE TITLE
NullReferenceException with V4.X when using long?[]

### ISSUE THREAD

**Issue by KolyaNET** [dadhi/FastExpressionCompiler#405]
Hello. I used FastExpressionCompiler version 3.3.4 and everything worked. After updating to version 4.1.0 I started getting errors. I also use Mapster 7.4.0.

I was able to find the problem using a NUnit test

```
using FastExpressionCompiler;
using Mapster;
using NUnit.Framework;

namespace Garda.Unit.Tests.Mapster;

[TestFixture]
[Parallelizable(ParallelScope.Default)]
internal sealed class NullItemArrayFastExpressionCompilerTests
{
    private sealed record ExportInfoDto(long[] Locations);

    private sealed record ExportInfoModel(long?[] Locations);

    private class ReportAdaptRule : TypeAdapterRule
    {
        internal ReportAdaptRule()
        {
            TypeAdapterConfig<ExportInfoModel, ExportInfoDto>
                .NewConfig();
        }
    }

    [TestCase(CompilerFlags.Default)]
    [TestCase(CompilerFlags.NoInvocationLambdaInlining)]
    [TestCase(CompilerFlags.EnableDelegateDebugInfo)]
    [TestCase(CompilerFlags.ThrowOnNotSupportedExpression)]
    public void NullItemArray(CompilerFlags compilerFlags)
    {
        // Arrange
        var report = new ExportInfoModel(new long?[] { 1 });

        TypeAdapterConfig.RulesTemplate.Add(new ReportAdaptRule());

        TypeAdapterConfig.GlobalSettings.Compiler = exp => exp.CompileFast(flags: compilerFlags);
        TypeAdapterConfig.GlobalSettings.Compile();

        // Act
        Assert.Throws<NullReferenceException>(() => report.Adapt<ExportInfoDto>());
    }
}
```
If I change long?[] to long[] or return version 3.3.4 then the NullReferenceException will no longer occur

Similar problems:
- https://github.com/dadhi/FastExpressionCompiler/issues/406
- https://github.com/dadhi/FastExpressionCompiler/issues/381
- https://github.com/MapsterMapper/Mapster/issues/676

**Comment by dadhi** [comment]
@KolyaNET Hi, thanks for the Test and the references to the similar issues.

As I understood, the problem is with mapping `long?[]` to `long[]` or is it the other way around?

If it is from `long?[]` to `long[]` what happens with nulls, are they skipped?

**Comment by dadhi** [comment]
@KolyaNET The [test](https://github.com/dadhi/FastExpressionCompiler/commit/850fc9d99c40d34e1ac6f6768bd7c66d5cb18580) is passing in the latest code, so it is hopefully fixed.
