### ISSUE TITLE
Incorrect il when passing by ref value

### ISSUE THREAD

**Issue by quifi** [dadhi/FastExpressionCompiler#414]
2 of 3 test cases in the attachment source file, passed when compiled by system expression, but failed by FastExpressionCompiler.

My environment:

- Windows 10, VS 2022
- .Net 8.0
- Newest FastExpressCompiler code from github

For example
````
int f(ref int x) => x;
````
emits
```
ldarg.1
(missing ldind.i4)
ret
```

[ByRef.zip](https://github.com/user-attachments/files/15891054/ByRef.zip)

**Comment by dadhi** [comment]
@quifi Confirmed, will look for the fix.
