### ISSUE TITLE
what's the difference between System.Linq.Expression and FastExpressionCompiler.LightExpression when using Expression<Func<T, object>>

### ISSUE THREAD

**Issue by goldli** [dadhi/FastExpressionCompiler#425]
hi, am i late?
today, when i try to replace `System.Linq.Expression ` to `FastExpressionCompiler.LightExpression`.  i got an error , 

> Error (active)	CS1660	Cannot convert lambda expression to type 'Expression<Func<UserInfo, object>>' because it is not a delegate type	

there are snaps
`using System.Linq.Expression`
![2024-10-19_084144](https://github.com/user-attachments/assets/94e088d8-778a-4e3c-af33-1b2af5c898a9)

`using FastExpressionCompiler.LightExpression`
![2024-10-19_084251](https://github.com/user-attachments/assets/57e80f59-f7be-417b-8a14-97643168d45e)

how to fix it ?

**Comment by dadhi** [comment]
@goldli You cannot fix it in a sense, that your lambda is actually a "hoisted" System Expression, created behind the scenes by the Roslyn. 
LightExpression.Expression may replace the System Expression constructed by hand, e.g. `Expression.Lambda<Func<int>>(Expression.Constant(42))`. But it cannot replace the Roslyn mechanics producing the same thing automatically for you when you're assigning a lambda like this `Expression<Func<int>> = () => 42`.

A possible way to mitigate it in future is to convert the System Expression produced by lambda into the LightExpression before using it in a bigger LightExpression tree. This conversation is not yet implemented but planned in #271

**Comment by goldli** [comment]
@dadhi , Thanks for explain. it's helpful.

**Comment by goldli** [comment]
@dadhi , Thanks for explain. it's helpful.
