### ISSUE TITLE
TryCatch - Bad label content in ILGenerator

### ISSUE THREAD

**Issue by snakex64** [dadhi/FastExpressionCompiler#430]
Hi!

I keep getting "Bad label content in ILGenerator" when I try to compile a small try..catch expression, either I get it directly when I call "CompileFast" or I get it when I try to create the type if I use it with "CompileFastToIL".

The issue seems to be around the "return 10" inside the "Catch". It does the same behavior if I "return" inside the "try".

I have been trying to compile an expression that represent represent something like this:
```cs
try{
    Call();
}
catch(Exception)
{
    return 10;
}
Call();
return 1;
```

I wrote this tiny demo Expression to replicate the issue:
```cs
var returnLabelTarget = Expression.Label(typeof(int), "ReturnLabel");

var tryBody = Expression.Call(typeof(Console).GetMethod("Clear")!);
var catchBody = Expression.Return(returnLabelTarget, Expression.Constant(10));

var tryCatch = Expression.TryCatch(tryBody, Expression.Catch(typeof(Exception), catchBody));

var afterCatch = Expression.Block(
	Expression.Call(typeof(Console).GetMethod("Clear")!),
	Expression.Return(returnLabelTarget, Expression.Constant(5)),
	Expression.Label(returnLabelTarget, Expression.Constant(0)));

var body = Expression.Block(tryCatch, afterCatch);

var expression = Expression.Lambda(body);

var v = expression.CompileFast();
```

Any idea what I'm doing wrong?

**Comment by dadhi** [comment]
Thanks for reporting. I will check.

**Comment by dadhi** [comment]
I have repro the bug.
But in order to do that I was needed to change your expression, as it is not passing the normal validation.
Check the valid test expression here https://github.com/dadhi/FastExpressionCompiler/commit/9c8c2e46f0dd99ea38f654389d4caced49582451

**Comment by snakex64** [comment]
> I have repro the bug. But in order to do that I was needed to change your expression, as it is not passing the normal validation. Check the valid test expression here [9c8c2e4](https://github.com/dadhi/FastExpressionCompiler/commit/9c8c2e46f0dd99ea38f654389d4caced49582451)

Amazing, thank you! Huge thanks for the whole library too. It completely saved me when I realized that Microsoft removed the "CompileToMethod" in .NET Core. I'm using this in a visual programming environment project, couldn't do it without your library

https://imgur.com/a/nlkfLLw
