### ISSUE TITLE
Support all for ExpressionInfo that is currently supported by Expression

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#46]
TryCatch, Block, Condition, Coalesc, Ariphmetic ops

**Comment by dzmitry-lahoda** [comment]
I have heard that expression are somewhat badly designed in its API sometimes. So making 1 to 1 may be not the best thing to do. 

Anyway there some other compile time staticaly typed AST for inspirations:

Dotty Tasty -  `AST persistence – the ability to persist trees at compile time after the typechecking and load them at runtime. TASTY is a typed AST serialization.`
F# Code Quotations https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/code-quotations

I guess F# did more things right then C# LINQ did.

**Comment by jogibear9988** [comment]
Goto and Label is also missing

**Comment by dadhi** [comment]
Will be covered by #66

**Comment by jogibear9988** [comment]
I think this is now also fixed, cause we test most tests against both

**Comment by dadhi** [comment]
yep.
