### ISSUE TITLE
[Challenge] ExpressionInfo for async await pattern

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#47]
Expression does not suport `async await` probably due whole lot of machinery required for its full implementation.

But FEC is just a library, not a .Net framework to cover everything.
In addition FEC has its own `ExpressionInfo`.
We can start from simple cases, e.g. async lambdas and methods, and await the call or property.

**Comment by dzmitry-lahoda** [comment]
As I got item is not about next
```
using System;
. using System.Collections.Generic;
. using System.Linq;
. using System.Linq.Expressions;
. using System.Text;
. using System.Threading.Tasks;
. 
. 
. async Task<int> X()
. {
.   return  await Task.FromResult(1);
. }
. 
. 
. public void Y(Expression<Func<Task<int>>> e) {
.     var c = e.Compile();
.     Console.WriteLine(c().Result);
. }
. Expression<Func<Task<int>>> ee = async () => await X();
. Y(ee);
. 
(19,34): error CS1989: Async lambda expressions cannot be converted to expression tree
```

**Comment by dadhi** [comment]
@dzmitry-lahoda We won't be able to support hoisted expression, 
but can leverage FEC custom `ExpressionInfo`.
Imagine something lime this:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using static FastExpressionCompiler.ExpressionInfo;

public class Program
{
    public static async Task<int> X()
    {
      return await Task.FromResult(1);
    }

    public static async Task Main()
    {
        // AsyncLambda and Await are new (need to be created) methods in ExprssionInfo
        var e = AsyncLambda<Func<Task<int>>>(Await(Call(
            typeof(Program).GetMethod(nameof(X))
        ))); 
        var f = e.CompileFast(true);
        Console.WriteLine(await f());
    }
}
```

**Comment by dadhi** [comment]
ASP .NET Core ObjectMethodExecutor in shared ASP sources used referenced in #72.
It creates custom awaitable struct for making async calls.

**Comment by dadhi** [comment]
I don't know how it can be used

**Comment by avonwyss** [comment]
I just published a lib which does exactly this, just in case you're interested.
https://github.com/avonwyss/bsn.AsyncLambdaExpression

**Comment by dadhi** [comment]
@avonwyss Hi, interesting. I will look to see if I can learn (steal) something :)

**Comment by dadhi** [comment]
outdated
