### ISSUE TITLE
Why the result is incorrect?

### ISSUE THREAD

**Issue by OscarKoo** [dadhi/FastExpressionCompiler#49]
I found your solution of optimizing LambdaExpression.Compile() from Google, and I've tried your latest version (1.5.0), which is really cool and fast, but...the result after running my application is weird.

I have NOT changed any logic of my code, just replaced "expression.Compile()" with "expression.CompileFast()" in my code and then ran it.

First one is the correct result (original result) that I expected.
![correct](https://user-images.githubusercontent.com/14313034/32954738-eb7e496c-cbee-11e7-8cc1-77b02d74f309.png)

Second one is what "expression.CompileFast()" does, and the only matched number is the last number...why?
![wrong](https://user-images.githubusercontent.com/14313034/32954783-09b70ab8-cbef-11e7-93ee-331e57474f83.png)

**Comment by dadhi** [comment]
Hi, what kind of expressions are you using?

Btw, obviously it is some kind of bug, but I won't be able to help and fix it until I have a failing sample.

**Comment by OscarKoo** [comment]
Thanks for reply!

I have traced the code and found the place of bug:

The logic is trying to get those "AvailableDate <= date" data, the variable "date" is changeable, and current value is "2017-01-02", but you can see, I picked one of the "query" result, and its AvailableDate is "2017-11-14", which is incorrect and it seems method "Where2" doesn't work...
![weird](https://user-images.githubusercontent.com/14313034/32976220-e2c98846-cc4c-11e7-9b54-16895cc905c3.png)

Here is what method "Where2" exactly do, It's just a simple switcher of IQueryable and IEnumerable, if "source" is IEnumerable, it will call "Enumerable.Where" by compiling the "Expression".
BTW, you can see the watch of "predicate.CompileFast()" from last picture.
![where2](https://user-images.githubusercontent.com/14313034/32976293-10bb2290-cc4e-11e7-9018-cd39f689d13d.png)

"FakeQuery" is a simple class as well, its purpose is trying to return the IEnumerator for those IEnumerable source.
![fakequery](https://user-images.githubusercontent.com/14313034/32976331-8f79b632-cc4e-11e7-9245-b4f824ae6ea7.png)

Are these clues helpful? I hope these clues could help you to find out the bug...

**Comment by dadhi** [comment]
It helps a lot. `AvailableDate <= date` is the main culprit. Will check it from here.

Btw, FastExpressionCompiler does not now anything in regard to `IQueryable` or `IEnumarable`, it just compiles the expression. Where and how it is composed does not matter.

**Comment by dadhi** [comment]
@OscarKoo , I have likely fixed this issue.

To confirm you may directly download the file https://github.com/dadhi/FastExpressionCompiler/blob/master/src/FastExpressionCompiler/FastExpressionCompiler.cs, and add it to your project.

I will release the fix on NuGet in upcoming days.

**Comment by OscarKoo** [comment]
@dadhi 
Thank you, but I have to wait your new release, because my visual studio is vs2013 which can not build your project.

And it's not urgent for me, so I can wait. and thanks for your quick fix!
