### ISSUE TITLE
System.InvalidProgramException

### ISSUE THREAD

**Issue by OscarKoo** [dadhi/FastExpressionCompiler#50]
@dadhi 

I newly got this Exception on testing server.
"
System.InvalidProgramException: Common Language Runtime detected an invalid program.
at (Closure`5 , TimeSlice )
at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
at Csh.Hcis.GC.VueScheduler.Common.Extensions.LinqExtensions.<AnyAsync2>d__11`1.MoveNext()
" 

Here is the code:
![20171121155927](https://user-images.githubusercontent.com/14313034/33061055-91dc0b80-ced5-11e7-9178-1323e295d5fe.png)

Here is the compiled delegate, it has 5 same variables (strange?).
![20171121155741](https://user-images.githubusercontent.com/14313034/33061107-c7bb187c-ced5-11e7-85e5-3d78dd2205f1.png)

Is there any clue?

**Comment by dadhi** [comment]
Interesting, as I understood whatever is inside `Where2` is expression to compile?
If so, what is the type of `w`, `w.DateType` and `w.Id` ?

**Comment by OscarKoo** [comment]
"whatever is inside Where2 is expression to compile" - Yes, as last time the picture I showed you. (if you remember)

"what is the type of w, w.DateType and w.Id?" - w is an Entity "class", w.DateType is "int", w.Id is "string".
public class TimeSlice
{
    public string Id { get; set; }
    public byte[] RowVersion { get; set; }
    public string ModalityId { get; set; }
    public int DateType { get; set; }
    public DateTime AvailableDate { get; set; }
    public string StartTime { get; set; }
    public string EndTime { get; set; }
    public int Duration { get; set; }
    public int TimeSliceType { get; set; }
    public int? MaxNumber { get; set; }
    public int? MaxPercentage { get; set; }
    public string Description { get; set; }
}

**Comment by dadhi** [comment]
Thanks for the info, I will get it from here.

**Comment by dadhi** [comment]
Hi @OscarKoo ,

I have added the [sample test here](https://github.com/dadhi/FastExpressionCompiler/blob/20c520b88e15b05afffb7f4e7e5cf5cb36779849/test/FastExpressionCompiler.UnitTests/EqualityOperatorsTests.cs#L58) and it is working just fine with the latest source.

Did you check on the latest source or v1.5?

**Comment by OscarKoo** [comment]
@dadhi 
Yes, I used your latest source which you gave me in the last issue.

Since there is no vs2015 on my machine, so I have to download "msbuild 2015" to build your dll. (https://www.microsoft.com/en-us/download/confirmation.aspx?id=48159)

And this Exception only happens on the testing server (not on my machine). and the testing server is windows server 2008 R2 (with .net framework 4.5.1), and my machine is windows7 (with .net framework 4.5.1). 

I'm not sure whether this Execption only happens in my particular scenario, either the way I built the dll or the testing server environment...

If you can not find anything wrong, maybe I have to wait your new upcoming release and try again. Thanks for your investigation.

**Comment by dadhi** [comment]
Check the v1.6 if it is still reproducible.

**Comment by OscarKoo** [comment]
Same exception in v1.6...

System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at (Closure`5 , TimeSlice )
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)

**Comment by dadhi** [comment]
Hi @OscarKoo,

Thanks for checking. I will try to reproduce.

**Comment by dadhi** [comment]
@OscarKoo,

May I ask you to add the Test below with the sample Entity class into Test project with NUnit, targeting the same .net 4.5.1 and try to run it?

       [Test]
        public void Complex_expression_with_DateTime_Strings_and_Int()
        {
            var dtNow = DateTime.Now;
            var version = new Entity { DateType = 1, AvailableDate = dtNow };
            var startTime = "b"; // a <= b
            var endTime = "x"; // y >= x
            var timeSliceId = "42";

            Expression<Func<Entity, bool>> e = w =>
                w.DateType == version.DateType &&
                w.AvailableDate == version.AvailableDate &&
                string.Compare(w.StartTime, startTime) <= 0 &&
                string.Compare(w.EndTime, endTime) >= 0 &&
                w.Id != timeSliceId;

            var f = e.CompileFast(true);


            var tested = new Entity
            {
                DateType = 1, AvailableDate = dtNow,
                StartTime = "a", EndTime = "y"
            };
            Assert.IsTrue(f(tested));
        }

        public class Entity
        {
            public string Id { get; set; }
            public int  DateType { get; set; }
            public string StartTime { get; set; }
            public string EndTime { get; set; }
            public DateTime AvailableDate { get; set; }
        }

**Comment by dadhi** [comment]
Hi @OscarKoo,
I have released v1.9 which improves handling of ValueTypes, and may fix this issue. Is it possible for you to check?

**Comment by dadhi** [comment]
Outdated, closing.
