### ISSUE TITLE
Execution slow-down, or incorrect use?

### ISSUE THREAD

**Issue by KristianWedberg** [dadhi/FastExpressionCompiler#52]
Hi,

In the compiled delegates below (adding two ints), using FastExpressionCompiler the _execution_ time is consistently 16% and 65% slower than using standard BCL expressions. Any idea why, or am I using it incorrectly?

Thanks,
Kristian

ETSumBCL: 164 ms
ETSumCompileFastInfo: 191 ms (+16%)
ETSumCompileFast: 271 ms (+65%)

```C#
// using Fast = FastExpressionCompiler;
// using FastPEI = FastExpressionCompiler.ParameterExpressionInfo;

            Time("Expression", ETSum());
            Time("Expression Compile Fast Info", ETSumCompileFastInfo());
            Time("Expression Compile Fast", ETSumCompileFast());

             Func<int, int, int> ETSum()
            {
                var aExp = Expression.Parameter(typeof(int), "a");
                var bExp = Expression.Parameter(typeof(int), "b");

                return Expression.Lambda<Func<int, int, int>>(
                    Expression.Add(aExp, bExp), aExp, bExp).Compile();
            }

            Func<int, int, int> ETSumCompileFastInfo()
            {
                var aExp = FastPEI.Parameter(typeof(int), "a");
                var bExp = FastPEI.Parameter(typeof(int), "b");

                return Fast.ExpressionCompiler.CompileFast<Func<int, int, int>>(
                    FastPEI.Lambda(Expression.Add(aExp, bExp), aExp, bExp)
                    );
            }

            Func<int, int, int> ETSumCompileFast()
            {
                var aExp = Expression.Parameter(typeof(int), "a");
                var bExp = Expression.Parameter(typeof(int), "b");

                return Fast.ExpressionCompiler.CompileFast<Func<int, int, int>>(
                    Expression.Lambda(Expression.Add(aExp, bExp), aExp, bExp)
                    );
            }

        private static void Time(String name, Func<Int32, Int32, Int32> fn)
        {
            int result = 0;
            Stopwatch sw = new Stopwatch();
            sw.Start();
            for (Int32 index = 0; index <= 100000000; index++)
            {
                result += fn(index, 1);
            }
            sw.Stop();
            Console.WriteLine($"{name}: {sw.ElapsedMilliseconds} ms{result.ToString().Substring(0, 0)}");
        }
```

**Comment by dadhi** [comment]
Can you do the same benchmark with [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet)?

It provides much more robust evaluation and stats for multiple possible platforms, Jits.

I am using it here: https://github.com/dadhi/FastExpressionCompiler/tree/master/test/FastExpressionCompiler.Benchmarks

**Comment by dadhi** [comment]
Can you do the same benchmark with [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet)?

It provides much more robust evaluation and stats for multiple possible platforms, Jits.

I am using it here: https://github.com/dadhi/FastExpressionCompiler/tree/master/test/FastExpressionCompiler.Benchmarks

Given the results we may decide what to do next.

**Comment by dadhi** [comment]
I have checked with BDN and did not found any issue. I've also added case with `ExpressionInfo` as fastest (__the Scaled column__). `ExpressionInfo.Add` was not available, so I've added it too. The results are below. The `ExpressionInfo.Add` will be available in the next version:

![image](https://user-images.githubusercontent.com/39516/36261830-b5f24928-1276-11e8-90ff-334fca15e5e0.png)

**Comment by dadhi** [comment]
Oops, sorry. For some reason I misunderstand it to measure a compile time and not an execution tim. Will re-check Tomorrow.

**Comment by dadhi** [comment]
I am observing the slowdown on this case (a+b):

![image](https://user-images.githubusercontent.com/39516/36301013-79bcdd12-1314-11e8-9701-9e28aadc257d.png)

From the debugging I see the same IL is generated.  Moreover I see the same ASM using BDN `DisassemblyDiagnoser` So __if anyone can help with ideas__, I will be grateful.

May be this case somehow optimized cause __I don't see a slow down in other cases__

**Comment by dadhi** [comment]
Even more interesting results on different invocation of (a+b):

![image](https://user-images.githubusercontent.com/39516/36305222-b277df94-1323-11e8-9d7a-d16467883fb5.png)

Strange that normally compiled expression is 25% faster than a bare lambda.

**Comment by dadhi** [comment]
Found the [related question in StackOverflow](https://stackoverflow.com/questions/24802222/performance-of-expression-trees/44233174#44233174) without a definite answer. But there are the same benchmark results with compiled lambda faster than direct delegate.

**Comment by EamonNerbonne** [comment]
I'm pretty sure this is a JIT "bug".  You could call it an interesting optimization choice, too ;-).

Because if you try this code, which is a little closer to what Expression.Compile does, then CompileFast's output is faster:

```C#
    class Bla
    {
        public static readonly Bla Instance = new Bla();
        public readonly int SomeValue = 3;
    }
```

```C#
            var aExp = Expression.Parameter(typeof(int), "a");
            var bExp = Expression.Parameter(typeof(int), "b");
            return Expression.Lambda<Func<int, int, int>>(Expression.Add(aExp, Expression.Field(Expression.Constant(Bla.Instance), typeof(Bla).GetField( "SomeValue"))), aExp, bExp);
```

Basically, Expression.Compile *always* adds a closure object, and that extra baggage makes the JIT... faster?  It's crazy, but hey...

**Comment by dadhi** [comment]
Interesting. But until I see an actual IL or better jitted ASM it is not clear.

I am currently building, stealing, looking for ILVisualizer for compiled delegate.

Couple of alternatives:

1. https://github.com/drewnoakes/il-visualizer
2. https://github.com/bartdesmet/ExpressionFutures/tree/master/CSharpExpressions/Tests.Microsoft.CodeAnalysis.CSharp.Helpers/ILVisualizer
3. https://github.com/longda/roslyn/tree/89169a3380e48fc834c72e38355867881d030e94/Src/Test/PdbUtilities/Metadata

**Comment by dzmitry-lahoda** [comment]
Is it still an issues I may look at?

**Comment by dadhi** [comment]
Yes, you can look but likely it is a some glitch.

**Comment by dadhi** [comment]
Linking #225

**Comment by dadhi** [comment]
New results after fixing #225

![image](https://user-images.githubusercontent.com/39516/64926066-ba14c100-d801-11e9-987f-6dc7517a6d7a.png)

Proof me wrong ;-)
