### ISSUE TITLE
Diagnostics for not supported expression

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#53]
Currently the only "diagnostic" is `null` returned from `CompileFast(true)`.

Ideally I want to know what sub-expression caused this null, and as much context as possible.

**Comment by jogibear9988** [comment]
May we should replace the "return false" via a method call "ReturnFalseOrThrow()"

And in this method we introduce a new Parameter to CompileFast => shouldThrow or smth similiar

**Comment by MichalBrylka** [comment]
Hi, I'd love to have any diagnostic support.
Any chance that something similar might be implemented ?

**Comment by MichalBrylka** [comment]
I can help with implementing that if you wish

**Comment by dadhi** [comment]
Give me a simple example how the usage would look like?

**Comment by MichalBrylka** [comment]
Hi,
I'm aware that CompileFast can accept bool ifFastFailedReturnNull parameter to fall back to standard Compile() method but it somehow ruins the point of using your library. It would be good if, when something is not implemented, appropriate exception would be thrown detailing which node is not supported. 
I have a fairly simple expression tree (if, method calls, property getter etc) to compile but CompileFast fails - would be nice to know quickly where I can try to make a pool request ;-)

**Comment by dadhi** [comment]
The exception will be fine, but only if respective option is passed - not by default (for now).
I would've turn the parameter to `CompileFast` from bool to enum - it is my mistake to not do this initially. `enum IfCompileFastFails {  FallbackToSystemCompile, ReturnNull, Throw }`.

PR would be good :)

**Comment by MichalBrylka** [comment]
well - that's weird. I'm pretty convinced that, when I used CompileFast from nuget, it failed. But today I've downloaded the code from github, started debugging and it seems to work ;-)
Anyway - diagnostics would be nice to avoid such stuff in future. 

I can help with PR if you need - just say so. In my company we are big fans of your work in DryIoC - we use it for 3 years in very complex and fast solutions. So I'd be glad to help

**Comment by dadhi** [comment]
Suddenly there goes the update from the other side #269.
When converting the final expression (likely to be composed of the smaller parts by some kind of pipeline) into its construction syntax - the output will contain `NOT_SUPPORTED_EXPRRESION_TYPE: FooBar`. 
So the test or assert may verify the presence of the not supported expression.

**Comment by dadhi** [comment]
**TODO:** Add this information into readme.md
