### ISSUE TITLE
Diagnostics for emitted IL code

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#54]
The FEC may generate different IL and therefore may display different __execution__ performance for the result delegate.

There is also question of correctness and easy of debugging.

It also should simplify new features implementation, etc. etc.

Really strange, that the project was able to get to this point without such thing.

For all these purposes we need an ability to dump the resulting IL, so it can be compared with standard IL produced by C# compiler.

**Comment by dadhi** [comment]
Ok, it was a lot of words. What exactly should we do:
1. Output the IL for fast compiled delegate.
2. Output the IL for normally compiled delegate.
3. If possible output target Asm for both.
4. IL output obviously should not affect compulation.

**Comment by dadhi** [comment]
Existing options

1. https://github.com/drewnoakes/il-visualizer
2. https://github.com/bartdesmet/ExpressionFutures/tree/master/CSharpExpressions/Tests.Microsoft.CodeAnalysis.CSharp.Helpers/ILVisualizer
3. https://github.com/longda/roslyn/tree/89169a3380e48fc834c72e38355867881d030e94/Src/Test/PdbUtilities/Metadata

**Comment by dadhi** [comment]
Here is working IL Visualizer for VS 2017: https://github.com/dadhi/il-visualizer

**Comment by dadhi** [comment]
The produced IL is the same :)

    IL_0000: ldarg.1    
    IL_0001: ldarg.2    
    IL_0002: add        
    IL_0003: ret

**Comment by dzmitry-lahoda** [comment]
My current approach:
![image](https://user-images.githubusercontent.com/757125/37240655-a81d08e2-245f-11e8-9495-93284a92e258.png)

https://en.wikipedia.org/wiki/List_of_CIL_instructions

**Comment by dzmitry-lahoda** [comment]
2017 support https://github.com/drewnoakes/il-visualizer merged into main repository. So may start and use only that.

**Comment by dadhi** [comment]
Yep, I was also thinking to add it to readme, tine-saver for me, especially in debug.

**Comment by dadhi** [comment]
The new diagnostics instruments available from the `TestTools` class:

- `PrintIL()`
- `PrintCSharpString()`
- `AssertOpCodes()`
