### ISSUE TITLE
Support compiling delegates with ref and out parameters

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#59]
Related: #55

**Comment by dadhi** [comment]
Here is the [test to fix](https://github.com/dadhi/FastExpressionCompiler/blob/master/test/FastExpressionCompiler.IssueTests/Issue55_CompileFast_crash_with_ref_parameter.cs) to return not a null from `FastCompile` but a working delegate.

**Comment by dzmitry-lahoda** [comment]
Ref in cases have very basic IL like next
```
.method public hidebysig 
	instance void Set (
		int32& obj
	) cil managed 
{
	// Method begins at RVA 0x2909
	// Code size 4 (0x4)
	.maxstack 8

	// obj = 7;
	IL_0000: ldarg.1
	IL_0001: ldc.i4.7
	IL_0002: stind.i4
	// (no C# code)
	IL_0003: ret
} // end of method Issue55_CompileFast_crash_with_ref_parameter::Set
```
I was able to generate it, but it where not well organized hacks in compiler. So added tests just to cover more cases, need may be 5 more tests, more complex, to have good solutions. And also method to be sure did not changes generation performance.

**Comment by rikimaru0345** [comment]
+1
The focus of this library seems (?) to be on performance, so ref parameters are pretty essential.

@dadhi  Any ideas when ref parameters will be supported? We want to use this for a serializer where most of the parameters are passed by ref.

`void Serialize(ref byte[] buffer, ref int offset, T value);`
`void Deserialize(byte[] buffer, ref int offset, ref T value);`

I don't think I can help with the ref parameters, but I will take a look at convenience methods like 
`AddAssign()`. (Otherwise we'd have to convert a lot of code from AddAssign to Assign+Add manually).

**Comment by dzmitry-lahoda** [comment]
https://github.com/dadhi/FastExpressionCompiler/pull/77

**Comment by dzmitry-lahoda** [comment]
Do early exit in https://github.com/dadhi/FastExpressionCompiler/blob/67746e8f1f2f4dafe6156717c257c1a874672390/src/FastExpressionCompiler/FastExpressionCompiler.cs#L418

   // TODO:
    // 1. multi ref set values
    // 2. `out` (out must be set - validate?)
    // 3. IntPtr and object ref tests
    // 4. check support of `in` https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/in-parameter-modifier


remove as https://github.com/dadhi/FastExpressionCompiler/blob/67746e8f1f2f4dafe6156717c257c1a874672390/src/FastExpressionCompiler/FastExpressionCompiler.cs#L1670 

as all done

5. Test calling of ref methods inside ref, passing refs, reading refs into local vars.

**Comment by dzmitry-lahoda** [comment]
Calling ref method inside ref fails and IntPtr usage fails #84 . I think after fixing these we will get `whole` support and story can be closed.

**Comment by rikimaru0345** [comment]
@dzmitry-lahoda
I will test it in the next one or two days. 
A project I'm working on makes heavy use of ref in all sorts of scenarios. I will report back later, but I might have to take a look at support for AddAssign/MultiplyAssign/... first (otherwise I will probably have to fix hundreds of callsites)

**Comment by dzmitry-lahoda** [comment]
#90 fixed ref cases

Created issue for AddAssign #91

**Comment by dzmitry-lahoda** [comment]
@dadhi , could we close this?
@rikimaru0345 , seems you may try.

**Comment by dadhi** [comment]
closing

**Comment by rikimaru0345** [comment]
I tried it, I'm still getting `Managed Debugging Assistant 'FatalExecutionEngineError' ` in the deserializer.

It has this definition: `delegate void DynamicDeserializer(byte[] buffer, ref int offset, ref T value);`, maybe that helps...

The code is pretty simple, so if needed I can extract it into a small test or something. Let me know.

**Comment by rikimaru0345** [comment]
Hi, I'll post the code here and make a pull-request with a test later when I have more time.

```


		delegate void DynamicDeserializer<T>(byte[] buffer, ref int offset, ref T value);

		static void FastExpressionCompilerTest<T>()
		{
			byte[] data = { 1, 8, 4, 4, 97, 98, 99 };

			var specificType = typeof(SetName);

			var bufferArg = Expression.Parameter(typeof(byte[]), "buffer");
			var refOffsetArg = Expression.Parameter(typeof(int).MakeByRefType(), "offset");
			var refValueArg = Expression.Parameter(typeof(T).MakeByRefType(), "value");

			List<Expression> block = new List<Expression>();


			Expression newObj;

			// if (!specificType.IsValueType)
			{
				// ReferenceType / Object
				var ctor = specificType.GetConstructor(Type.EmptyTypes);
				if (ctor == null)
					throw new InvalidOperationException("Cannot compile formatter " +
														"for type " + specificType.Name + " because it has " +
														"no parameterless constructor, thus cannot be instantiated when deserializing");

				var createNew = Expression.Convert(Expression.New(ctor), typeof(T));

				// Long if block removed here that is not taken
				{
					newObj = Expression.Coalesce(refValueArg, createNew);
				}
			}
			// else block removed


			block.Add(Expression.Assign(refValueArg, newObj));


			// Cast it to the specific type we actually need (so we can assign the specific fields)
			var valAsSpecific = Expression.Variable(specificType, "valAsSpecific");
			block.Add(Expression.Assign(valAsSpecific, Expression.Convert(refValueArg, specificType)));

			/*

			// Go through all fields and assign them
			foreach (var fieldInfo in fields)
			{
				// - todo: respect attribute to use a specific formatter here as well (HalfFloat, Int32Fixed) 

				var formatter = _serializer.GetFormatter(fieldInfo.FieldType, extraErrorInformation: $"DynamicObjectFormatter ObjectType: {specificType.FullName} FieldType: {fieldInfo.FieldType.FullName}");
				var deserializeMethod = formatter.GetType().GetMethod(nameof(IFormatter<int>.Deserialize));

				Debug.Assert(deserializeMethod != null, "Can't find deserialize method on formatter");

				var fieldExp = Expression.Field(valAsSpecific, fieldInfo);

				var serializeCall = Expression.Call(Expression.Constant(formatter), deserializeMethod, bufferArg, refOffsetArg, fieldExp);
				block.Add(serializeCall);
			}
			*/



			if (specificType.IsValueType)
				// If we're dealing with a value type, we have to write back from local-variable to ref-parameter
				// todo: warn the user that reference serialization with structs is very wonky in any case, and can't really be fixed
				// maybe we can deserialize reference fields to local vars, and keep track of the objectIDs that are supposed to go in there, then write them again or something?
				block.Add(Expression.Assign(refValueArg, Expression.Convert(valAsSpecific, typeof(T))));


			var serializeBlock = Expression.Block(variables: new[] { valAsSpecific }, expressions: block);
#if true
			var d = Expression.Lambda<DynamicDeserializer<T>>(serializeBlock, bufferArg, refOffsetArg, refValueArg).CompileFast(true);
			
			
			var offset = 0;
			T obj = default(T);
			d(data, ref offset, ref obj);
#else
			return Expression.Lambda<DynamicDeserializer<T>>(serializeBlock, bufferArg, refOffsetArg, refValueArg).Compile();
#endif
		}


call it with `object`: `FastExpressionCompilerTest<object>();`


I removed as much code as possible to make the method small while still leaving the bug.

**Comment by dzmitry-lahoda** [comment]
I will fix it.

**Comment by dadhi** [comment]
@dzmitry-lahoda Until _dev_branch is merged, please consider to fix this on the _dev_ branch.
Work in FEC.cs is 99% done, so you will get fewer merge-conflicts.

**Comment by dzmitry-lahoda** [comment]
Ok, but as of now I have to think deeply. FEC gives IL similar to Roslyn, but broken. IL of LINQ and FEC/Roslyn differ greatly. I got new IL keywords regarding ref stuff to learn. Hope to fix within week.
```
        [Test]
        [Ignore("Fix it")]
        public void CoalesceIntoByRef()
        {
            void DynamicDeserializer<T>(ref T value) where T:class, new () =>
                value = value ?? new T();

            var specificType = typeof(object);
            var valueRef = Parameter(typeof(object).MakeByRefType(), "value");
            var newObj = Coalesce(valueRef, New(specificType.GetConstructor(Type.EmptyTypes)));
            var xVar = Variable(specificType, "x");
            var lambda = Lambda<ActionRef<object>>(
                    Block(new[] { xVar }, Assign(valueRef, newObj)),
                    valueRef
                );

            var compiledFast = lambda.CompileFast(true);
            var compiled = lambda.Compile();

            void LocalAssert(ActionRef<object> invoke)
            {
                var obj = default(object);
                invoke(ref obj);
                Assert.AreNotEqual(default(object), obj);
            }

            LocalAssert(compiled);
            LocalAssert(DynamicDeserializer);
            LocalAssert(compiledFast);
        }
```

**Comment by dzmitry-lahoda** [comment]
@dadhi Seems I have fixed almost like one liner via #114. Would you be able to merge? I thought to make IL like in LINQ, but appears we better with like in Roslyn.

Intresting, that `generic` generated for Roslyn may appear to be slower than `generic` by FEC. Not sure what is perf difference of LINQ vs FEC.

**Comment by dadhi** [comment]
I probably be able to merge, but not automatically. Can you cherry pick it to _dev_ branch?

**Comment by jogibear9988** [comment]
is this fixed?

**Comment by dzmitry-lahoda** [comment]
yes. it is in master now.

**Comment by jogibear9988** [comment]
close?
