### ISSUE TITLE
Better strategy to split code between Expression and ExpressionInfo

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#66]
Current approach is mix and max with a lot of copy-paste. Hopefully, we can devise a strategy:

### 1 Split the code completely, may be even move to separate file and package.

Pros:
- Simple to achieve
- More performant cause requires less run-time switches
- Flexible in regards of adding new features into ExprInfo
- Less noise for those who don't need ExprInfo

Cons:
- Changes and Fixes should be copied between two
- Two files/packages to support 

### 2 Abstract over both and have single source code for both

Pros:
- One compact code-base, no need to copy changes and fixes
- One package to support

Cons:
- Harder to-do and may impact performance due switch logic
- Likely, less flexible when adding the new features or changing ExprInfo alone

**Comment by dadhi** [comment]
### 3 Convert Expression to ExpressionInfo and handle the latter

I may use the approach from [sum-types](https://gist.github.com/dadhi/815cf2ef8e88b555c59be7e4be93e712) to make ExpressionInfo cases a structs under the ExpressionInfo class, implementing the same interface. That's will ensure the performance of conversion from Expression to EI struct. 

Given that C# 7 enables `in` (by ref) semantics for struct parameters, the result IE can be passed to `TryEmit..` methods in efficient manner.

This + migrating to C# 7+ may be a goal for __v2.0__

**Comment by jogibear9988** [comment]
The current strategy makes the Code much more complex. wouldn't it be possible to Generate Code only for normal "Expressions" and create a second .cs file via T4 for ExpressionInfo?
So we put "using static System.Linq.Expressions.Expression;" and change this via the T4 Template for ExpressionInfo?

**Comment by dadhi** [comment]
Ok may be we are at the point to split. 

I did not consider T4 but did consider a split.

**Bonus points** except code simplification are:

- Not performance loss due casting and matching Expr vs ExpressionInfo, and no need in proxy types.
- The full parity beteen both will be automatic.

Technically, how the template should look like?

```
<# T4 directives ... #>
using static FastExpressionCompiler.ExpressionInfo;
<#@ include File="$(SolitionDir)\Shared\FastExpressionCompiler.cs" #>
```

**Comment by jogibear9988** [comment]
I think you should have at least 2 source files.

One with the complete parsing code and "using static System.Linq.Expressions.Expression;" at the top.

One file with the complete ExpressionInfo type definitions.

And a T4 Template wich replaces the "using static System.Linq.Expressions.Expression;" at the top.

**Comment by dadhi** [comment]
Putting `using static` aside there other things to consider.

I want and do in DryIoc use both Ecpr and ExprInfo in the same class. That means I need to prevent conflicts via either names (`Info` suffix) or via different namespaces.

There are method that accept Expr and ExprInfo as parameters. I would like to remove the midfke ground `object` parameters. In this case `using static` won't help, cause parameter names should be fully stated.

Then we may remove `Info` suffix, but need to use a new namespace, to enable non-conflicting usage.

**Comment by dadhi** [comment]
I think we may start with moving `ExpressionInfo` to separate file.

Then remove all the noize from FEC related to ExprInfo.

At the end we may just copy FEC.cs to new project with ExprInfo.cs and make it work, preserving minimal changes. Better 1, or 2 line changes.

Then move all tests for ExprInfo to separate project.

If everything compiles - works, it will be a very good step.

Then the new FECWithExprInfo package.

We may even dismiss or postpone T4.

**Comment by jogibear9988** [comment]
when will you start doing this?

**Comment by dadhi** [comment]
Depends. I may start after merging your requests, maybe later Today or Tomorrow.
I but I don't think I'll finish in one swoop. Maybe a couple of days.

**Comment by dadhi** [comment]
The work is going on in `dev` branch

**Comment by jogibear9988** [comment]
As you now already have breaking changes, maybe it's a good idea to remove obsolete API's ?

**Comment by dadhi** [comment]
Good idea!

**Comment by jogibear9988** [comment]
maybe we should also modify the tests that most of them work with Expression and LightExpression

**Comment by jogibear9988** [comment]
maybe we could also do this with conditional compilation?

**Comment by dadhi** [comment]
Already doing so. At the end I will link all the Unit and Issue tests (which is make sense) to the respective LE tests.

You may check `AssignTests` and `BockTests`  already for how I am doing so.

**Comment by jogibear9988** [comment]
split is finished?

**Comment by dadhi** [comment]
The main part is finished. 
What remains is the incremental addition of Tests (Unit and Issues) for FEC.LE, and adding whatever is missed in FEC.LE.Expression.cs

The tests may be added one-by-one without affecting other fixes. Therefore moving to master.

**Comment by dzmitry-lahoda** [comment]
I may cover `ref` related method within several weeks if not yet. Other vice I may do `math` operators.

**Comment by jogibear9988** [comment]
I've converted all test where possible (GitHub issues not yet)

But the ones wich include a Expression created from c# compiler are not converted! I also think we should test c# compiler generated expressions, so we should not change this tests. If we need them also for LightExpression we need to create new ones.

**Comment by jogibear9988** [comment]
I'm working on all the GH issues tests. think 20min

**Comment by jogibear9988** [comment]
problem:

this line:

      expression = field == null ? Property(expression, property) : Field(expression, field);

does not work with light expression, because Property && Field return different types! what should I do?

**Comment by jogibear9988** [comment]
I now changed the return type to MemberExpression
