### ISSUE TITLE
Equality comparison with nullables throws at delegate-invoke

### ISSUE THREAD

**Issue by Banjobeni** [dadhi/FastExpressionCompiler#67]
The following expressions compile successfully, but exceptions are thrown during execution of the resulting delegates. The first is the one i'd actually like to use, and the second is a failed attempt to circumvent the first.

```C#
        class Foo {
            public int? Prop { get; set; }
        }

        static void Main(string[] args) {
            int int32Comparand = 1;
            Expression<Func<Foo, bool>> a = foo => foo.Prop == int32Comparand;

            var ac = a.CompileFast();
            var ar1 = ac(new Foo { Prop = null }); // throws NullReferenceException
            var ar2 = ac(new Foo { Prop = 1 }); // throws NullReferenceException

            Expression<Func<Foo, bool>> b = foo => Nullable.Equals(foo.Prop, null);

            var bc = b.CompileFast();
            var br1 = bc(new Foo { Prop = null }); // throws AccessViolationException
        }
```

**Comment by dadhi** [comment]
Thanks for posting, will look.

**Comment by Banjobeni** [comment]
FYI, this is close to what the C# compiler generates for `Int32?` equality comparison:

```C#
if(a.GetValueOrDefault() != b.GetValueOrDefault()) {
    return false;
}
return a.HasValue == b.HasValue
```

**Comment by dadhi** [comment]
What is the version of FEC ?

**Comment by Banjobeni** [comment]
I downloaded the master branch as zip today and added the .cs to my toy project in order to reproduce the bug. Should be the most recent version available.

**Comment by Banjobeni** [comment]
Thanks, wow, that was fast! Although this still does not allow for my use case to completely rely on FastExpressionCompiler, at least the situation is more clear now.
I'd appreciate it if you'd mention the unsupported nullable comparison in the readme - this would be a time saver if I were in the same situation again of thinking about using FEC.

**Comment by dadhi** [comment]
Yep, may be will try to include more info into release notes. It was a fast fox, cause no exception better than exception. I hope someone will help with #67 to enable the capability in FEC :)
