### ISSUE TITLE
Support comparison and equality of Nullable and different left and right types

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#68]
Related to #67 

Note: That `Nullable.Equals` is supported now and can be used as workaround.

**Comment by jogibear9988** [comment]
Support for Nullable is implemented.

still missing are different left & right types!   (for example nullable int with nullable)

**Comment by jogibear9988** [comment]
Are different left and right Types really possible?

Expression.Equals for example throws when trying to create with int & int? or when trying to compare int & double.

If not, we can close this, as Nullable's are now supported!

**Comment by dadhi** [comment]
Ehat if int and int? are converted to object?
If it is supported, we can close.

**Comment by jogibear9988** [comment]
don‘t know. i think it would use object equals
