### ISSUE TITLE
Unity

### ISSUE THREAD

**Issue by ENikS** [dadhi/FastExpressionCompiler#69]
Максим привет,

Я пишу новый движок к Unity, хочу модернизировать старичка, и подумал, а ты не хочешь поучаствовать? Думаю, что твой опыт мог бы пригодиться :)

Я собираюсь переписать все на C# 7.2+, добавить ASYNC, полностью оптимизировать движок и сделать dynamic pipelines. Открыть API и воткнуть крючки, где надо. Короче, много чего интересного.

Я знаю, что ты продолжаешь работать над DryIoc, но я не думаю, что одно помешает другому. 
В общем подумай...

**Comment by dadhi** [comment]
Привет Женя,

Я рад что Unity возраждается.

Но к сожалению, у меня много других интересов и слишком мало времени.
Поэтому активно и вовлеченно помочь не смогу :(

Частично, выделение FEC и ImTools и есть способ помочь другим похожим проектам с тулингом, ну и получить более надежные поддерживаемые инструменты для себя.

Плюс есть совершенно другие вещи, которые не хочу забрасывать, типа XamlTea. А также планы на статьи, конференции и т.д. Тут документацию про DryIoc и плагинам еще писать и писать.

Но я слежу за репозиторием Unity, и стараюсь быть в курсе. 
Если вдруг появится конкретный вопрос, постараюсь помочь.

Удачи!
