### ISSUE TITLE
Try CompileFast for MS.Extensions.ObjectMethodExecutor

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#72]
There is a shared source package used at least by ASP .NET Core:  
https://github.com/aspnet/Common/blob/ff87989d893b000aac1bfef0157c92be1f04f714/shared/Microsoft.Extensions.ObjectMethodExecutor.Sources/ObjectMethodExecutor.cs

Here is the umbrella post by @shanselman  
https://www.hanselman.com/blog/ASPNETCoreArchitectDavidFowlersHiddenGemsIn21.aspx

and respective tweet by @davidfowl  
https://twitter.com/davidfowl/status/1004237863913906176

I may guess if FEC works, the benifits may be neglectible.
Anyway, it is a good real world case, let's check :)

**Comment by davidfowl** [comment]
Interested in the outcome. Keep me posted.

**Comment by dadhi** [comment]
Status: the `await ExecuteAsync()` for compiled fast async executor is crashing. 
But executing without await, just returning `Task` works. 

 I have added tests [6b203fd](https://github.com/dadhi/FastExpressionCompiler/commit/6b203fde437a765173f5560a21cb0374a0c376bc) to demonstrate the issue.

**Comment by dadhi** [comment]
Found culprit, this expression inside `GetExecutorAsync`:

![image](https://user-images.githubusercontent.com/39516/42898181-1ac4004a-8acb-11e8-95a9-036a96385934.png)

The problem is probably due `CustomAwaitableType` being a struct, and then with converting the whole result to `object`. The good news is that expression is quite simple and __can be checked in isolation to find the problem__.

Without converting this particular expression above to `CompileFast` the results are:

__Compilation:__

![image](https://user-images.githubusercontent.com/39516/42898150-03edf1f0-8acb-11e8-86ee-cd446460949a.png)

__Execution:__
![image](https://user-images.githubusercontent.com/39516/42897753-a2e96d0e-8ac9-11e8-9a94-39a15a9c0db2.png)

The compilation has a room for improvements - here is the illustration how changing the last (problematic) expression to `CompileFast` adds up:

![image](https://user-images.githubusercontent.com/39516/42898667-7285d906-8acc-11e8-8d40-8263036f409e.png)

**Comment by dadhi** [comment]
Here is the Executor for `async` method with all `CompileFast` fixed:

__Sample method:__ `async Task<string> Foo(int a, int b) => await Task.FromResult((a + b).ToString());`

__Compilation:__
![image](https://user-images.githubusercontent.com/39516/43003405-16956cbe-8c35-11e8-8a44-f3e1431cc5f1.png)

__Execute (blocking):__
![image](https://user-images.githubusercontent.com/39516/43003717-1a7507ee-8c36-11e8-963a-93f785bc0b9d.png)

__ExecuteAsync:__
![image](https://user-images.githubusercontent.com/39516/43003965-e62c2ca0-8c36-11e8-8b95-9a2bbb72924f.png)

**Comment by dadhi** [comment]
Sync method: 
`string Foo(int a, int b) => (a + b).ToString();`

__Compilation:__

![image](https://user-images.githubusercontent.com/39516/43014579-4f6d8ae2-8c55-11e8-91f7-43ce408e093b.png)

__Execution:__
todo

**Comment by dadhi** [comment]
Benchmarks with BDN 0.11 including .NET Core results:

## Async method executor

### Compilation:

![image](https://user-images.githubusercontent.com/39516/43143291-1da246cc-8f63-11e8-8dd5-6b3648cdb001.png)

### ExecuteAsync:

![image](https://user-images.githubusercontent.com/39516/43144100-fcc22c9a-8f64-11e8-9681-681d3329a92b.png)

### Execute sync blocking:

![image](https://user-images.githubusercontent.com/39516/43144546-148cd568-8f66-11e8-8625-f98549e520b5.png)

**Comment by dadhi** [comment]
/cc @davidfowl 
v1.9.0 is out with the fixes enabling results above (with `.Compile` replaced with `.CompileFast`)

**Comment by dadhi** [comment]
Using #75 (v1.10.0):

![image](https://user-images.githubusercontent.com/39516/43585623-40be3618-966e-11e8-9ae7-af65761d1ca7.png)

**Comment by dadhi** [comment]
/ccL @davidfowl 

Here are the results from __V2__ with _FEC.LightExpression.Expression_ added as the baseline:

![image](https://user-images.githubusercontent.com/39516/45211454-fd595d00-b29a-11e8-8dbc-dc3ce8d84d18.png)
