### ISSUE TITLE
Tried with Moq and some tests failed

### ISSUE THREAD

**Issue by informatorius** [dadhi/FastExpressionCompiler#73]
I tried to use FastExpressionCompiler inside Moq source code replacing all Compile() calls with CompileFast(). Most Moq.Tests succeeded but some failed.

**Comment by dadhi** [comment]
Let's fix them then :) What tests?
Ideally, could you add failing and ignored tests into FEC.IssueTests.

**Comment by informatorius** [comment]
1) Download https://github.com/moq/moq4 latest
2) Build all
3) Run Moq.Tests
=> 1000 tests succeeded
4) Edit 5 moq source files which use Expression.Compile() and replace with Expression.CompileFast()
5) Build all
6) Run Moq.Tests again
=> 4 out of 1000 tests failed

**Comment by dadhi** [comment]
Thanks for the steps! Btw, not bad :)
I would expect more tests to fail.

**Comment by informatorius** [comment]
It is good work so far.
