### ISSUE TITLE
What is the difference to `.CompileToMethod()` ?

### ISSUE THREAD

**Issue by rikimaru0345** [dadhi/FastExpressionCompiler#74]
There is a method called `.CompileToMethod()` inside `LambdaExpression` as well that takes a MethodBuilder, what if we use that directly? Would it not be possible to configure a MethodBuilder in a way so that nothing gets added that slows the compiled expression down?

Is there more than just the "skipVisibility" flag that is causing slowdowns?
Is the default expression compiler actually generating slow code or inserting checks that we know could be avoided? Is that the reason why we're doing the whole emitting to MethodBuilder ourselves with this project?

**Comment by dadhi** [comment]
Hi @rikimaru0345 ,

`.CompileToMethod()` compiles to the method in __new generated assembly__, here is the performance hit - in order to get `MethodBuilder` first you need to create Assembly, Module and Type :) The result method will be a "bit" faster than `.Compile()` result, due no special sand-boxing required.

`.Compile` creates a `static` delegate in the _current_ assembly.

**Comment by rikimaru0345** [comment]
I see.

So it's only a compile-time performance hit, right?

Do you think it would be possible to somehow "hack" the internal LambdaCompiler class that LambdaExpression.Compile() uses. By maybe forcing it to set the `skipVisibility` flag, or giving it some other MethodBuilder somewhere.... maybe even emulating/rebuilding parts of it if the functions are really incompatible and then calling other parts through reflection?

I don't care much about compile-performance, but runtime performance is important, so my idea was to reuse as much as possible from the existing classes and logic that's already there in LambdaExpression and its internal LambdaCompiler.

I explored that for a bit, but I'm not sure if it would even work out.
The first issue I hit was that LambdaCompiler **really does need** a parent type, because it uses it to store the new classes it generates for captured variables and constants. 
(And you're solving it by [doing it yourself](https://github.com/dadhi/FastExpressionCompiler/blob/7b2adf15085f136b370245c99308f5563999f725/src/FastExpressionCompiler/FastExpressionCompiler.cs#L610))


So that's why there's really no way to solve this the "easy way" somehow and writing our own IL is the only way, is that right?

I guess you really invested some time to make sure there's no easier way than essentially building your own Expression compiler.

**Comment by dadhi** [comment]
> I guess you really invested some time to make sure there's no easier way than essentially building your own Expression compiler

Mostly yes. May be there is way, but compilation time was always important for me, so I did not really explore other extremes.

**Comment by dadhi** [comment]
Will be closing then. Feel free to reopen if you have an idea how to proceed.

**Comment by Timovzl** [comment]
I'm trying to get a picture of the execution performance, but I couldn't gather it from the answers here.

If execution performance of the generated code is all we care about, might we just as well use `CompileToMethod`, or does FastExpressionCompiler offer a meaningful improvement here too?

**Comment by dadhi** [comment]
@Timovzl 

The correct answer is to measure it for your case.
From my experience (and the bechmarks) you will have a slight performace boost up-to 20 percent for the expression of the modest size and complexity (avoiding too many conditions, try-catchs, etc.)

In some cases when you're using nested lambdas you might see 100x perf. boost.

In some cases with complex expressions you may see a decrease up-to 20 percent.
Though I believe it is an opportunity for the improvement and fix. 
So if you found the quirky abd reproducible case, please submit.
