### ISSUE TITLE
Consider naming of TryCompileWithPreCreatedClosure

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dadhi/FastExpressionCompiler#82]
https://github.com/dadhi/FastExpressionCompiler/blob/master/src/FastExpressionCompiler/FastExpressionCompiler.cs#L276

```
public static TDelegate TryCompileWithPreCreatedClosure<TDelegate>(this LambdaExpressionInfo lambdaExpr,
            object closure, params object[] closureConstantsExprs)
```

1. Need to look into spec of C#, but seems `closure` is `delegate`, and `variables` are `captures`. TryCompileWithPreCreatedClosure. So name TryCompileWithPreCreatedCapture. 
2. But `closure` and `closureConstantsExprs` are already in API and should be documented as `params` as `captures`. So my do `TryCompile`. C# is not Eiffel to put `params` into method name when possible. 
3. Also not sure why `object` in API. May be more strict types possible?
4. May be add see also to Microsoft docs about closure captures, or document as in C++ explicit captures are documented.
5. `Try` means I may try often. But when `Try` fails if capture missed, it is EXCEPTION. Not normal flow. And code should be fixed. So throw `Exception` if possible to distinguish? And remove `Try`. Is `Try` legacy of time when FEC supported to few features?

In C++ `Constructs a closure: an unnamed function object capable of capturing variables in scope. `
https://en.cppreference.com/w/cpp/language/lambda

**Comment by dzmitry-lahoda** [comment]
# Naming 
The need to pass additional parameter makes method `long`, need to know for it is for. `Try` in name makes it dangerous(unsafe,unchecked), at least suggesting to read summary of method when it will be `false` or `true`.

https://www.ecma-international.org/publications/files/ECMA-ST/Ecma-334.pdf

Mentiones `capture` 30 times, in context of variables being capture by lambda or anonymous function.

https://en.wikipedia.org/wiki/Closure_(computer_programming)

```
closure is a record storing a function[a] together with an environment.[1] The environment is a mapping associating each free variable of the function (variables that are used locally, but defined in an enclosing scope) with the value or reference to which the name was bound when the closure was created.[b] A closure—unlike a plain function—allows the function to access those captured variables through the closure's copies of their values or references, even when the function is invoked outside their scope. 
```

So C++, C# spec and wiki ,as I read, will be `closure = lambda + captures`.  What text states that closure is capture? I believe unproper naming if the case may confuse.

Hm https://stackoverflow.com/a/9592254/173073

```
// same name for all compiles(discovery), until not try is used
// need to know specific is documented via parameters (could at least check capture.NotNull())
// Unsafe alternative may mean that CLR will fail on execution of bad IL
TDelegate {Unsafe|Try}Compile<TDelegate>(this LambdaExpression lambdaExpr,
            SpecificTypeIfPossibleNotObject_IfObjectThenDocumentedAsTypeParam capture{s})
where TDelegate : Delegate;

TDelegate TryCompile<TDelegate>(this LambdaExpression lambdaExpr)
where TDelegate : Delegate;

TDelegate {Unsafe|Try}Compile{Static|NOCaptures}<TDelegate>(this LambdaExpression lambdaExpr)
where TDelegate : Delegate;
````

# Errors

Sources of `errors`:
- Bugs in FEC.
- FEC does not supports feature yet.
- Simple parameter validation like NotNull.
- Trying to compile function with `bad IL` (wrong tree or captures or other parameters passed).
- Call function with `bad IL` (i.e. no proper `capture` was considered)

Reaction on errors:
- Throw during compilation.
- Return null.
- Trow during call with some CLR error
- Hidden errors when all is like fine, but after call function does not do its job (e.g. forgers to set value or what ever).

I see that FEC is not clear (at least for end user - me) in this regard, and possibly:
- put table sources/reactions{/cases} onto table{hyper} and ensure all is consistent
- write down returns to clarify (and may be modify FEC) for return types



```
    /// <summary>Tries to compile lambda expression to <typeparamref name="TDelegate"/> 
        /// with the provided closure object and constant expressions (or lack there of) -
        /// Constant expression should be the in order of Fields in closure object!
        /// Note 1: Use it on your own risk - FEC won't verify the expression is compile-able with passed closure, it is up to you!
        /// Note 2: The expression with NESTED LAMBDA IS NOT SUPPORTED!</summary>
        public static TDelegate TryCompileWithPreCreatedClosure<TDelegate>(this LambdaExpression lambdaExpr,
object closure, params ConstantExpression[] closureConstantsExprs)
```

`return` is not documented. In what cases try will fail and what consequences? I guess method can return compiled object and than throw on call? Or throw during complication? May it is `Unsafe`(if bad program exception or clr unable to execute) or `Dangerous`? But not try.

**Comment by dadhi** [comment]
I think the current amount of info is enough but I am open for PR. CLosing.

**Comment by dzmitry-lahoda** [comment]
Closed issues are not voted. I guess we have 2 votes. One is yours which fine with both naming. And mine naming which knows that naming should be changed, but not enough votes from possible users for rename work. So keeping it open will allow people to vote.

**Comment by dadhi** [comment]
I predict no-one will vote, but let's keep it open. No problem.

**Comment by dadhi** [comment]
No one voted, closing.
