### ISSUE TITLE
Issues with linq2db tests

### ISSUE THREAD

**Issue by MaceWindu** [dadhi/FastExpressionCompiler#83]
Similar to #73 I'm trying to evaluate if it makes sense to have support for custom expression compiler in linq2db.

Right now we have a lot of tests that fail with exceptions, hangs or incorrect results. I've used custom build using version from master branch as we need signed assembly to run our tests.

Does it make sense to create issue for each failure or you can try to run our tests and fix issues you receive?

Linq2db version with required changes is available here: https://github.com/linq2db/linq2db/pull/1277

To run tests you will need to create test configuration file UserDataProviders.json (as copy of DataProviders.json) and comment-out all databases from NET45 test configuration to run generic non-database tests. This will give you 10 failing tests.

After that you can uncomment providers one-by-one to run database tests. Those are sqlite/access tests, so they don't need any extra environment setup.

If you want, I can invite you to our slack chat to have faster communication.

**Comment by dadhi** [comment]
> If you want, I can invite you to our slack chat to have faster communication.

Not for this week, I am on vacation.

> Does it make sense to create issue for each failure or you can try to run our tests and fix issues you receive?

Won't be able to run your tests, at least for a couple of weeks. But may be someone else can? /cc @dzmitry-lahoda

May be, there is a similar error in a group of tests. So you can create less than 10 issues.

Otherwise, start one by one, better with isolated failed test. The tests for issues can be added to _FastExpressionCompiler.IssueTests_ project. See already added tests for example. You should initially `Ignore` the failing tests. PR is welcome.

**Comment by dzmitry-lahoda** [comment]
@MaceWindu, hopefully you could create `FastExpressionCompiler.IssueTests.Issue83_Linq2db` with all tests extracted from `linq2db`. This greatly reduces barrier of occasional fixes and increases changes somebody from the wild will look into, problem defined and covered.

**Comment by MaceWindu** [comment]
Ok, but don't think I will be able to look at it before weekend

**Comment by jogibear9988** [comment]
Mhmmm...

This Code produces the same expression:

            var pParam = Expression.Parameter(typeof(string), "p");

            var condition = Expression.Condition(Expression.NotEqual(pParam, Expression.Constant(null)),
                Expression.Convert(pParam, typeof(int), typeof(int).GetMethod("Parse", new[] {typeof(string)})),
                Expression.Constant(0));
            var lambda = Expression.Lambda<Func<string, int>>(condition, pParam);
            var convert1 = lambda.CompileFast();
            var convert2 = lambda.Compile();

            var p = "10";
            var c1 = convert1(p);
            var c2 = convert2(p);

            Assert.AreEqual(c1, c2);

and it seems to work...

**Comment by jogibear9988** [comment]
Seems like this

   Expression.Convert(pParam, typeof(int), typeof(int).GetMethod("Parse", new[] {typeof(string)}))

is not yet supported!

**Comment by jogibear9988** [comment]
@dadhi I haven't seen, he already created tests ..  ;-(.

**Comment by jogibear9988** [comment]
for nullable char, maybe this is helpful

https://stackoverflow.com/questions/10888820/initializing-a-nullable-type-with-initobj-opcode-in-il

**Comment by jogibear9988** [comment]
I tried to look for the AccessViolationException_on_nullable_char_convert_to_object test.

What I do not understand, the working delegate from expression compile is the first IL Code window. But where is the 32 for the space char in this IL ?
The second one is from FastCompile()

<img width="1252" alt="bildschirmfoto 2018-08-24 um 19 50 15" src="https://user-images.githubusercontent.com/364896/44599606-2ed02400-a7d7-11e8-9803-cc54ae7f2858.png">

**Comment by dadhi** [comment]
Loaded from Closure array by index?

**Comment by jogibear9988** [comment]
and how can i see the il of the closure?

**Comment by dadhi** [comment]
no idea

**Comment by jogibear9988** [comment]
Now to the last error in Linq2DB Tests. This one is hard, think we need to simplify expression tree to find out

Workin IL Plotted to assembly
<img width="1680" alt="bildschirmfoto 2018-08-24 um 22 07 20" src="https://user-images.githubusercontent.com/364896/44605577-3d740680-a7ea-11e8-92cd-b3789a1206a0.png">

Not workin one:
<img width="1372" alt="bildschirmfoto 2018-08-24 um 22 09 02" src="https://user-images.githubusercontent.com/364896/44605610-5d0b2f00-a7ea-11e8-8990-d6bb047ab463.png">

**Comment by jogibear9988** [comment]
@dadhi can you help here?

**Comment by jogibear9988** [comment]
@MaceWindu do we also have the double cast in linq2db?

**Comment by jogibear9988** [comment]
@dadhi ok. thanks. will look if I could track down the error a little bit more.

**Comment by dadhi** [comment]
Also if you have a nested `Expression.Lambda` and then `Invoke` you may split it in two and `Compile(Fast)` separately. This way you may isolate the problem further.

**Comment by jogibear9988** [comment]
Maybe its because we do not use the result of CheckNullValue but it's left on the stack?

**Comment by jogibear9988** [comment]
It is the missing Pop...

Thought it could fix like this (in try emit Method call)

                if (!EmitMethodCall(il, method))
                    return false;

                if (parent == ExpressionType.Block)
                    il.Emit(OpCodes.Pop);

                return true;

but does not yet work. keep looking

**Comment by jogibear9988** [comment]
Now it works...

                if (!EmitMethodCall(il, method))
                    return false;

                if (parent == ExpressionType.Block && method.ReturnType != typeof(void))
                    il.Emit(OpCodes.Pop);

                return true;

**Comment by dadhi** [comment]
Yep, this is partially a reason for introducing a parent type - to have more context. Probably at some point we will need a whole stack, but hopefully not now.

**Comment by dadhi** [comment]
@MaceWindu @jogibear9988 ,
I have fixed the last (?) test failed. Fill free to grab v2-preview-02 to check. 
Will wait a bit and release 2.0.

**Comment by MaceWindu** [comment]
Sorry for delay. JUst checked our netfx and netcore tests with current FEC master - all green.

**Comment by dadhi** [comment]
Thanks, I still have some more fixes to do for nullables comparison. Then hopefully, will wrap-up on V2.
