### ISSUE TITLE
[Idea] Generate random expression trees for test

### ISSUE THREAD

**Issue by dadhi** [dadhi/FastExpressionCompiler#86]
Use property-based testing or similar (FsCheck, Expecto, other?) to generate random trees, compile and assert.

**Comment by dzmitry-lahoda** [comment]
One case would be not sonstrains, but combinations, e.g. {byte, int, long, float, ... , BigInteger} x {Sum, Divide, .. , Multi }  x {1 parameter, ... , 256 parameters}.

**Comment by dadhi** [comment]
Not for me, but I welcome whoever will try the fuzzing
