### ISSUE TITLE
Ref support not yet working completely

### ISSUE THREAD

**Issue by jogibear9988** [dadhi/FastExpressionCompiler#95]
This Code does not yet work:

        [Test]
        public void RefAssign()
        {
            var objRef = Expression.Parameter(typeof(double).MakeByRefType());
            var lambda = Expression.Lambda<ActionRef<double>>(Expression.Assign(objRef, Expression.Add(objRef, Expression.Constant((double)3.0))), objRef);

            var compiledA = lambda.Compile();
            var exampleA = 5.0;
            compiledA(ref exampleA);
            Assert.AreEqual(8.0, exampleA);

            var compiledB = lambda.CompileFast<ActionRef<double>>(true);
            var exampleB = 5.0;
            compiledB(ref exampleB);
            Assert.AreEqual(8.0, exampleB);
        }

**Comment by jogibear9988** [comment]
<img width="669" alt="bildschirmfoto 2018-08-22 um 22 38 42" src="https://user-images.githubusercontent.com/364896/44489615-31f2d500-a65c-11e8-8173-96e06b3af764.png">

**Comment by jogibear9988** [comment]
I'll check, maybe I have time to analyze this. But I'm not sure...

**Comment by dzmitry-lahoda** [comment]
I done byref #99

**Comment by jogibear9988** [comment]
thx

**Comment by jogibear9988** [comment]
fixed by #99
