### ISSUE TITLE
% and bit operators are not supported

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dadhi/FastExpressionCompiler#98]
[Test, Ignore("Fix it")]
        public void Can_modulus()
        {
            Expression<Func<short, short, long>> expr = (arg1, arg2) => arg1 % arg2;

            var multiplyFunc = expr.CompileFast(true);

            Assert.IsNotNull(multiplyFunc);
            Assert.AreEqual(1, multiplyFunc(7, 6));
        }

        [Test, Ignore("Fix all bit operations OR XOR AND")]
        public void Can_bitor_1()
        {
            Expression<Func<int, int, int>> expr = (arg1, arg2) => arg1 | arg2;

            var multiplyFunc = expr.CompileFast(true);

            Assert.IsNotNull(multiplyFunc);
            Assert.AreEqual(1, multiplyFunc(1, 1));
        }

**Comment by jogibear9988** [comment]
Think also of the "Assign" mode of many of those operations

AndAssign, ExclusiveOrAssign, OrAssign

**Comment by jogibear9988** [comment]
see #105 for a list

**Comment by jogibear9988** [comment]
fixed in #109

**Comment by jogibear9988** [comment]
can be closed
